### ISSUE TITLE
Update drupal core and some modules

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#116]
Hi Amanda.
I noticed that drupal has released several patches (Security update).
Can I to apply it for all sites?
![1](https://cloud.githubusercontent.com/assets/970967/5611001/f9ea34c6-94c8-11e4-9e66-437608a98f71.png)
![2](https://cloud.githubusercontent.com/assets/970967/5611000/f9e9bdca-94c8-11e4-9f2e-b479f71dda81.png)
![3](https://cloud.githubusercontent.com/assets/970967/5611002/f9ece162-94c8-11e4-9812-df86ffdbc799.png)

**Comment by AmandaBekhoj** [comment]
sure, thanks :)

**Comment by mamont77** [comment]
Fixed.
