### ISSUE TITLE
export user list

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#117]
Hi Ruslan, 

Is it possible to export the list and information of advisors from Drupal, to get it into an excel file?

We need to know who 'ticked' off the SMS service :)

**Comment by mamont77** [comment]
Currently impossible. I think it is not difficult to make a similar function. I will do today.

**Comment by AmandaBekhoj** [comment]
thanks :D

**Comment by mamont77** [comment]
Amanda, try this.
1. Go to http://www.skillspeople.dk/admin/people (Home » Administration » People).
2. To scroll down, you will see two icons (csv and xls).
![people skillspeople - referral recruitment kobenhavn - google 01-09-2015 15 16 17](https://cloud.githubusercontent.com/assets/970967/5680213/b317f284-9812-11e4-95e5-2dcab028b7af.png)
3. Click any icon.
4. Open in Exel.
Can I add or remove fields.

**Comment by AmandaBekhoj** [comment]
Perfect! you are my hero. 

i have one question - do you know what it means when there is either nothing, 0, or a 1 in the 'SMS enabled column?

i guess 0 is when people have unsubscribed the SMS service, but why is the space empty for some, and others have a 1?

**Comment by mamont77** [comment]
A value of 1 - enabled (mark set), 0 or empty - off.

0 - User manually unset checkbox.
empty - These are old people who have imported before we added the field.

**Comment by AmandaBekhoj** [comment]
ah okay, i would have hoped that all the old ones got the 'SMS alert' box checked, but that is too troublesome?

**Comment by mamont77** [comment]
Fixed.
0 or 1 now. Without empty.
You can fix any user quickly. ))

http://www.skillspeople.dk/admin/people
Step 1 - select users:
![people skillspeople - referral recruitment kobenhavn - google 01-09-2015 15 34 55](https://cloud.githubusercontent.com/assets/970967/5680382/45493a58-9815-11e4-91ab-0c2ff2eb6dc6.png)

Step 2 - set or unset a value:
![set parameters for change value skillspeople - referral recrui 01-09-2015 15 35 37](https://cloud.githubusercontent.com/assets/970967/5680392/5e08db2a-9815-11e4-8c94-3a13aa1189f5.png)

**Comment by AmandaBekhoj** [comment]
thanks :D have a nice weekend!
