### ISSUE TITLE
help with new page

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#118]
Hi Ruslan, i need help with a couple of things regarding a new page. 
SO, we want to make it possible to upload their CV and take a personality test on this site http://www.skillspeople.dk/tag-kandidattest 

1. we need an obvious link on the front-page (and i do not think there is room for any more menu-taps). so we were thinking that it might be clever to make a banner on the carousel that says 'TAG KANDIDATTEST' (take candidate test) .. something like this, but just prettier… and in same font as the rest of the page
![skaermbillede 2015-01-14 kl 10 39 50](https://cloud.githubusercontent.com/assets/8081414/5736803/87e68866-9bda-11e4-9e31-ccac5fb9b609.png)

2. we need boxes where candidates can write their information (name, phone, email, and current position) all these boxes should be mandatory. 

![skaermbillede 2015-01-14 kl 10 49 41](https://cloud.githubusercontent.com/assets/8081414/5736868/397733dc-9bdb-11e4-9dd4-689dfcd1deb0.png)

3. it should be possible for the candidate to upload their CV

4. then we need the 'Send ind' button (submit).. The test should not be able on the site from the beginning, because we need to link the personal information, CV and the test together. Is it possible to make the 'Send ind' button so it saves the information the candidate typed in, and also link to the test in a new window?

4. we need the CV and the candidate information to be connected and inserted in some sort of data base from where we can extract the information. i imagine something like this: 
![skaermbillede 2015-01-14 kl 10 52 14](https://cloud.githubusercontent.com/assets/8081414/5737039/fa93db1e-9bdc-11e4-9f88-92f98ab230cc.png)

5. when the candidate press 'Send ind' (submit) the boxes and CV upload disappear, and a text should appear (but only instead of the boxes and buttons, the original text in the top and button should still be available). the text should read 'Tak fordi du er blevet en del af SkillsPeoples kandidatdatabase, vi vil kontakte dig hvis der er et jobmatch.'

you think all this is possible? i know it is a lot. :)

**Comment by mamont77** [comment]
Nothing is impossible! Just one question about test. After the candidate sent the CV... Where the candidate will pass the test? On Drupal side or via e-mail or other place?
All what you have written above, I'm going to use this module https://www.drupal.org/project/webform.

**Comment by mamont77** [comment]
Amanda,

What type of field "Nuværende stilling"? Single-line text field or multi-line text field?

**Comment by AmandaBekhoj** [comment]
the test is in another place, called PLUM, where the candidate would have to create an account.. so i realize, that it might be hard to link the drupal information with the test information, but that is ok.. as long as CV and drupal information is linked, that is very important. 
I will have christian to make a link to the PLUM test. 

hm, i guess just single line for the 'Nuværende stilling' - but make it possible to write as many characters as possible.. or max 100 maybe?

**Comment by mamont77** [comment]
Also...
How can I get a link to the test for a current user?
Is it "Nuværende stilling" = "Current position"?
When the user filled out the form, must be sent an email?

**Comment by AmandaBekhoj** [comment]
and the site should off cause be 'open' to everyone, with a link to the front page in the form of a red banner, as i tried to show in point 1 :)

**Comment by AmandaBekhoj** [comment]
we are sending out separate emails for current users to take the test, we have a special database for them. 

this site is for new candidates, who are not advisors (maybe a little complicated :b )

yes, 'Nuværende stilling' = current position

No, we do not need to send out email. i imagined, that when you press the 'Send ind* (submit) then you get transferred to a new window, where you take the test. In the SkillePeople window, all the boxes and CV upload should be removed, and this text should be visible as italic 'Tak fordi du er blevet en del af SkillsPeoples kandidatdatabase, vi vil kontakte dig hvis der er et jobmatch.'

**Comment by mamont77** [comment]
In process.
http://www.skillspeople.dk/tag-kandidattest
http://www.skillspeople.dk/node/134/webform-results/table
http://www.skillspeople.dk/node/134/webform-results/download
I will write later, when you can check.

**Comment by AmandaBekhoj** [comment]
thanks! :D and i will write you when i have link for the PLUM test

**Comment by mamont77** [comment]
Amanda.
Please test the for only.
http://www.skillspeople.dk/tag-kandidattest
http://www.skillspeople.dk/node/134/webform-results/table
http://www.skillspeople.dk/node/134/webform-results/download
You can change "test link" here http://www.skillspeople.dk/node/134/webform/components/6?destination=node/134/webform (Hjem » Tag kandidattest » Redigér komponent: Test Link)

**Comment by AmandaBekhoj** [comment]
hm, i tried to send - but i am not sure anything happened? the boxes were still there after i pressed 'send ind' and i cannot find til information in the web form-results?

**Comment by AmandaBekhoj** [comment]
Also, we need two more boxes, both drop down menus. 

One should be called 'Hvor ønsker du job?' with drop down menu:
Københavnsområdet
Region Sjælland
Fyn
Nordjylland
Midtjylland
Sydjylland
Bornholm 

(it should be possible to choose more than one)

The other one should be called 'Erfarings niveau' with drop down menu:
Under 5 år
5-10 år
10-15 år
over 15 år


and here is the link that the 'Send ind' button should be linked to: http://bit.ly/1x4s7w3

**Comment by mamont77** [comment]
Amanda,
The form on http://bit.ly/1x4s7w3 page has a new form also. Fist name, last name... Drupal can not transfer data to another site that the user has just filled. Do you understand this?

I will add two new fields today.

**Comment by AmandaBekhoj** [comment]
yes i understand this, and it is okay :)

**Comment by mamont77** [comment]
1. Added the link on front page. The link visible for admin role only!
2. Added two fields.

Please test again.
I do not know why you have failed to submit the form.

Redirect to http://bit.ly/1x4s7w3 in process.

**Comment by mamont77** [comment]
Amanda, you should change "test link" in two spaces:
* http://www.skillspeople.dk/node/134/webform/configure (uses for redirect to test)
* http://www.skillspeople.dk/node/134/webform/components/6 (saved test's info to result)

**Comment by AmandaBekhoj** [comment]
i do not know what you mean about the changing the 'test link' ??

also, the link on the front page is not good.. i will see if i can figure out some way to make a banner there

**Comment by mamont77** [comment]
This link we can set manually. When to change the link to the test, you will change the value of the field.
![help with new page issue 118 mamont77 skillspeople - google 01-15-2015 14 28 13](https://cloud.githubusercontent.com/assets/970967/5757353/d63386a2-9cc2-11e4-83a0-870a6a007e9b.png)

**Comment by mamont77** [comment]
Other screen snap 
![tag kandidattest skillspeople - referral recruitment kobenhav 01-15-2015 14 30 03](https://cloud.githubusercontent.com/assets/970967/5757374/24382056-9cc3-11e4-8d71-7e96fd58d77b.png)

**Comment by AmandaBekhoj** [comment]
but i do not understand what i should change the test form to?

**Comment by mamont77** [comment]
* http://www.skillspeople.dk/node/134/webform/configure (uses for redirect to test only)
* http://www.skillspeople.dk/node/134/webform/components/6 (saved test's info to result)
When the link to test changes, you can change it in two place.
![rediger komponent test link skillspeople - referral recruitme 01-15-2015 14 45 49](https://cloud.githubusercontent.com/assets/970967/5757567/48a0084e-9cc5-11e4-9028-424c8326d3f1.png)
This link will be displayed in the results table.

**Comment by AmandaBekhoj** [comment]
but it won't change? it should be the same link every time :)

**Comment by mamont77** [comment]
If in the future, there will be another link ... If this link is constant, then why it is displayed in a table?

**Comment by AmandaBekhoj** [comment]
it does not have to be displayed in the table.. it was only because i though maybe it was possible to connect the drupal info and CV with the test result, but that is not possible. :)

I am sorry for confusing you!

When people submit their information, they should be redirected (in a new window) to the test, where they have to make some sort of 'account' beforee they can take the test. we will then connect the emails, if a candidate is relevant :)

**Comment by mamont77** [comment]
Got it now :-)
I do not know how to open the link in a new window. But I think of a way.

**Comment by AmandaBekhoj** [comment]
Perfect. 

also, the 'hvor ønsker du at arbejde' should also be a drop down menu as the 'erfarings niveau' .. and if it is possible to chose more than one?

aand, i just noticed, that 'Erfaringsniveau' is in one word, how do i fix?

**Comment by mamont77** [comment]
We can use like that http://cdn.sheknows.com/articles/2011/10/button-expert-tips-red.png or http://www.forextetrabot.com/pictures/Tips.png instead of red link. It's just an idea.

>> and, i just noticed, that 'Erfaringsniveau' is in one word, how do i fix?

Fixed here http://www.skillspeople.dk/node/134/webform

**Comment by AmandaBekhoj** [comment]
maybe like this? (but with the circle a little further to the right)
![skaermbillede 2015-01-15 kl 14 22 25](https://cloud.githubusercontent.com/assets/8081414/5758135/d5375422-9cc2-11e4-8bc5-986e9708f022.png)

also, the drop downs need to be like the 'erfaringsniveau' was before, where it says 'Vælg' (choose) and then you can choose from a list.

**Comment by mamont77** [comment]
Amanda
1. You can configure "thank you test" if need here http://www.skillspeople.dk/node/134/webform/configure
2.  'Vælg'  - It does not work in forms where you can select multiple values.

**Comment by mamont77** [comment]
Please test the button on front page and form of course.
![skillspeople - referral recruitment kobenhavn - google chrome 01-15-2015 16 28 26](https://cloud.githubusercontent.com/assets/970967/5759089/bff54d56-9cd3-11e4-87f5-aecfb0daf567.png)
![skillspeople - referral recruitment kobenhavn - google chrome 01-15-2015 16 28 47](https://cloud.githubusercontent.com/assets/970967/5759090/bff7e688-9cd3-11e4-9665-8580bd729012.png)

**Comment by AmandaBekhoj** [comment]
i do not know what i do wrong in the form, but it does not seam like my submission goes through? i can only see your tests?

**Comment by AmandaBekhoj** [comment]
but the button on the front page works fine! i hope the others like it!

**Comment by mamont77** [comment]
i tried use your account. and it is work to me.
![tag kandidattest skillspeople - referral recruitment kobenhav 01-15-2015 16 59 47](https://cloud.githubusercontent.com/assets/970967/5759676/13e95160-9cd8-11e4-8261-f5062d15934d.png)
can you show me in teamviewer or skype?

**Comment by AmandaBekhoj** [comment]
hm, now it says that i have already sent my formular.. so i guess it works :)

then the test just need to be linked with the 'send ind' button :)

**Comment by mamont77** [comment]
>>now it says that i have already sent my formular.

I added record using your account. Important for me to make sure that you and the other candidates can do it and it works. Please ping me in skype at any time. I want to see your screen.

**Comment by AmandaBekhoj** [comment]
hm, it is very weird.. 

i think i deleted the screen viewer thing, because my computer's hard disk was full. 

Have you found a solution for the 'Send ind' button and link to test?

**Comment by mamont77** [comment]
Yes. I found a solution and i want to test it. Please ping me in skype, when you have time.

**Comment by mamont77** [comment]
And you can edit this user http://www.skillspeople.dk/user/1415/edit

**Comment by AmandaBekhoj** [comment]
tried as guest, it worked really well!

![skaermbillede 2015-01-19 kl 16 32 31](https://cloud.githubusercontent.com/assets/8081414/5802835/eb7f6614-9ff8-11e4-8d7b-7bffd4c6d5d7.png)
![skaermbillede 2015-01-19 kl 16 32 42](https://cloud.githubusercontent.com/assets/8081414/5802837/edc16170-9ff8-11e4-8870-60c22711692c.png)

ecept, that when i wanted to chose two locations, instead of just choosing the two, it chose everyone in between as well.. 

and then the text on the skillspeople page (after send ind) should be different :)

**Comment by mamont77** [comment]
you can change the text.
before (above the form) http://www.skillspeople.dk/node/134/edit
after (look at "Bekræftelse" field) http://www.skillspeople.dk/node/134/webform/configure - this text is displayed after the user has filled in the form.

**Comment by AmandaBekhoj** [comment]
perfect, i changed it. 

can you make it available for everyone to see? :D

**Comment by mamont77** [comment]
Done. A block on front page is visible.

**Comment by AmandaBekhoj** [comment]
thanks :D
