### ISSUE TITLE
HELP ASAP!

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#119]
We need the 'CV upload' function on all of our job positions that people WITHOUT a login wishes to apply for. 

I should not be mandatory, but it should be an possibility. It should look like the one you made on the 'Tag kanddattest' site :)

![skaermbillede 2015-01-15 kl 11 29 03](https://cloud.githubusercontent.com/assets/8081414/5755899/0596ba5e-9caa-11e4-8125-6a50c622d111.png)

Also, we need the boxes to go away after the application has been sent, so it is obvious, that we received it. 

Can there be a text saying 'Tak for din ansøgning, vi kontakter dig hurtigst muligt.' 

can you fix quickly??

**Comment by mamont77** [comment]
I can not fix it quickly. This form is is built in another way without using a drupal module. I'll think about how to add a file field.
And it's not a bug, it's a new feature.

**Comment by AmandaBekhoj** [comment]
thanks!

sorry, i just added it to get your attention :b

**Comment by AmandaBekhoj** [comment]
but we are getting massive response on one of our positions, and people are confused that there is not a place to submit their CV, that is why we need it as fast as possible :)

**Comment by mamont77** [comment]
Please test this form. I temporary set $to = 'ab@infrahouse.com'.

**Comment by AmandaBekhoj** [comment]
WUHU it works, thanks!!

is it possible though, to make it more visible that the submission was successful? 
as a text saying 'Tak for din ansøgning, vi kontakter dig hurtigst muligt.' ? :)

**Comment by AmandaBekhoj** [comment]
I'm getting all your tests :)

**Comment by mamont77** [comment]
Done.
Increased font size and translated text.
![key account manager - glostrup - nianet skillspeople - referra 01-15-2015 15 16 55](https://cloud.githubusercontent.com/assets/970967/5757996/a66ff4da-9cc9-11e4-8f8f-abb79d80af45.png)
Can I remove your mail from form?

**Comment by AmandaBekhoj** [comment]
perfect! yes, please remove my email :)

**Comment by mamont77** [comment]
I have a wish for the future. Please don't write like "help asap" in title. Better "Add file field to form - asap" :-)

**Comment by AmandaBekhoj** [comment]
ofcourse! i will make sure to remember that :)
