### ISSUE TITLE
new editor

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#120]
Hi Ruslan

can you make svh@skillspeople.dk an editor to drupal? :) she will be managing our blogging and social media presence.

**Comment by mamont77** [comment]
Done http://www.skillspeople.dk/users/svh-svh.
The pass same as mail. He(she) must change the pass.

**Comment by AmandaBekhoj** [comment]
she can use it on salestribe.dk as well, yes?

**Comment by mamont77** [comment]
Nope! I added she to skillspeople site only.
Should I add it to the other two sites? salestribe.dk and infrahouse.com?

**Comment by AmandaBekhoj** [comment]
only salestribe.dk :D thanks!

**Comment by mamont77** [comment]
Should i remove in skillspeople? :)

**Comment by mamont77** [comment]
Done. http://www.salestribe.dk/users/svh-svh

**Comment by AmandaBekhoj** [comment]
thanks!

**Comment by AmandaBekhoj** [comment]
and do not remove in skillspeople :)
