### ISSUE TITLE
candidate references

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#122]
is it possible for us, in some way, to use drupal to see, which advisors (using their advisor IDs) have reffered which candidates?

somehow the information is not saved in out podio and workable workspaces. and it would be really useful for us to see, who is referring who :)

**Comment by mamont77** [comment]
That's interesting. Can you provide a real example for fictional characters? ))

**Comment by AmandaBekhoj** [comment]
Actually, i can provide you with a real example: 

Thomas Frost is an advisor, and he has reffered several candidates. 
BUT we cannot see, which candidates he has referred, and to which jobs.. and Thomas would really like to know, how the candidates are doing. 

can we find this information?

**Comment by mamont77** [comment]
I can do it on the side of Drupal. Tomorrow or the day after. Okay?

**Comment by AmandaBekhoj** [comment]
thanks! but will it then also be possible to see past referrals? or will it only be future referrals?

**Comment by mamont77** [comment]
Drupal and I can not know about Thomas and other people. ((
If this information was saved in Podio ...
This will work for future relations.

**Comment by AmandaBekhoj** [comment]
:( that is not very good! 

we have most information stored in podio, but we cannot seem to find who reffered who :(

but it will be possible from now on, or?

**Comment by mamont77** [comment]
Amanda, 

I'm sorry, I can not understand. This information is available in Podio or is missing?
Maybe I can get this data from Podio, if these data exists.

If this is not possible, we will have to implement it in Drupal. And of course we can not guess who refers to whom.

**Comment by AmandaBekhoj** [comment]
we do not know if it exists in podio, we cannot find it! but we have all the other information about the reffered candidates.. 

if the information does not exist at all in podio, we would like to have it implemented in drupal :)

**Comment by mamont77** [comment]
>>we have all the other information about the reffered candidates..

Where it is saved and in what format this info?

**Comment by AmandaBekhoj** [comment]
![skaermbillede 2015-01-22 kl 09 50 09](https://cloud.githubusercontent.com/assets/8081414/5852768/42c8efe2-a21c-11e4-96bc-2f3dc14d21d6.png)

**Comment by AmandaBekhoj** [comment]
actually, i am not sure, if the information is saved from durpal, or if someone from skills people receives  and email with some information which he has to write into podio

**Comment by AmandaBekhoj** [comment]
actually we just figured it out, so i will close this agin :)
sorry for the inconvenience!
