### ISSUE TITLE
the login

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#123]
So, we need to remove the login, since we are getting a new menu tap. 

We would like the login to be moved, just up in the corner (with the same font and color as it is now). when it is pressed, it should also look like it does now. 

![skaermbillede 2015-01-21 kl 16 29 41](https://cloud.githubusercontent.com/assets/8081414/5838929/04312e66-a18b-11e4-9462-f4271bf01245.png)

**Comment by mamont77** [comment]
I just put a label for me. This task depends on #125

**Comment by AmandaBekhoj** [comment]
oh okay.. why does it depend on #125 ?

**Comment by mamont77** [comment]
If I understand correctly, we should create a new menu (nav), and then move 'LogIn' link to a new menu.

**Comment by AmandaBekhoj** [comment]
im not sure of the term. but i do not think we need a new menu navigation? only a new menu tap, as the ones we have already, 'For virksomheder' 'Om os' 'Priser' and so on. but if we just add the 'For Kandidater' tap, the menu will be too long. that is why we need to move the login further up :)

**Comment by mamont77** [comment]
I got it now. Thanks you.

**Comment by mamont77** [comment]
Please check.

**Comment by AmandaBekhoj** [comment]
perfect, thanks :D
