### ISSUE TITLE
social media like buttons

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#124]
i know we have the social media links on the front page. BUT Christian also wants the 'like' button (where it likes our Facebook directly without opening Facebook) and then also then LinkedIn 'follow' button. it would be fine with logos of the two as well :)

it should be up beside the log-in. sooo. first the FB button, then the Linkedin button and lastly log-in (log in should be aligned with the design of the page of course)

Facebook link: https://www.facebook.com/Skillspeople
linkedin link: https://www.linkedin.com/company/skillspeople?trk=biz-companies-cym

**Comment by mamont77** [comment]
Do I correctly understand you?
An Advisor can not login to site until doesn't "Like/Follow" using 2 buttons.

**Comment by AmandaBekhoj** [comment]
nono, they should be able to login in always. 

we just want to make it possible for everyone to like skillspeople without going away from the site :)

**Comment by mamont77** [comment]
Sorry. Sometimes my technical basic English fails me :-(

Like that?
![hjem skillspeople - referral recruitment kobenhavn - google c 01-23-2015 15 17 20](https://cloud.githubusercontent.com/assets/970967/5875214/76f059e8-a313-11e4-8e23-3b98f4afca32.png)
In this beautiful design course.

**Comment by AmandaBekhoj** [comment]
hehe it is okay :D i lack the same skills!

but no, i was more thinking that they should be located here:
![skaermbillede 2015-01-23 kl 17 17 47](https://cloud.githubusercontent.com/assets/8081414/5877998/eb38efc6-a323-11e4-8a57-902d80ad5581.png)

and then both the Facebook like button and linkedin like button 
![skaermbillede 2015-01-23 kl 17 21 36](https://cloud.githubusercontent.com/assets/8081414/5878057/5db38c32-a324-11e4-93e4-2c17eb65b718.png)

does it make sense :) ?

**Comment by mamont77** [comment]
i got it :-D
thank you very much ))

**Comment by mamont77** [comment]
Hi Amanda,

Please check out the new functionality very carefully.

Results:
![skillspeople - referral recruitment kobenhavn - google chrome 01-28-2015 12 25 54](https://cloud.githubusercontent.com/assets/970967/5936219/f7a4d0c0-a6ea-11e4-87b6-d1504afab043.png)
![skillspeople - referral recruitment kobenhavn - google chrome 01-28-2015 12 26 22](https://cloud.githubusercontent.com/assets/970967/5936220/f7a7d6d0-a6ea-11e4-8854-7f6e86bb2240.png)

But for some unknown reason to me it looks bad for 14-16 inch monitors. I'm looking for a solution ....
![skillspeople - referral recruitment kobenhavn - google chrome 01-28-2015 12 25 26](https://cloud.githubusercontent.com/assets/970967/5936248/2a1a3036-a6eb-11e4-9c53-9498124f47af.png)

**Comment by AmandaBekhoj** [comment]
It looks fine on the website.
but it does not look good on mobile device, it is not aligned. 

furthermore, it is the wrong Facebook link, it should not be to the salestribe Facebook, but the skillspeople Facebook: link https://www.facebook.com/Skillspeople

**Comment by mamont77** [comment]
The url fixed.

Amanda, I did not understand anything about
>>  it does not look good on mobile device, it is not aligned.

Can you show?
My screensnaps:
![screenshot_2015-01-28-20-31-11](https://cloud.githubusercontent.com/assets/970967/5944225/f27801d8-a72d-11e4-8ab3-a12dc3df995a.png)
![screenshot_2015-01-28-20-31-20](https://cloud.githubusercontent.com/assets/970967/5944226/f27b2fca-a72d-11e4-8e55-3a249e576e0c.png)

And i can see one bug in red button, i willl file a new issue.
![screenshot_2015-01-28-20-32-18](https://cloud.githubusercontent.com/assets/970967/5944244/118826de-a72e-11e4-981a-d1c24e243c42.png)

**Comment by mamont77** [comment]
Other browser:
![screenshot_2015-01-28-20-56-54](https://cloud.githubusercontent.com/assets/970967/5944553/903139ba-a730-11e4-90e5-0f1c00c21c6f.png)
![screenshot_2015-01-28-20-57-05](https://cloud.githubusercontent.com/assets/970967/5944554/903430f2-a730-11e4-8eb1-fc391edf6cb5.png)

**Comment by AmandaBekhoj** [comment]
my screen on iPhone looks like this: 
![img_2001](https://cloud.githubusercontent.com/assets/8081414/5954757/01b3e252-a79c-11e4-818a-f06674512904.PNG)

you see it does not look good

**Comment by mamont77** [comment]
Thank you.

**Comment by mamont77** [comment]
Please check the page in the iPhone. Better or worse?
I gave my iPhone a child to watch cartoons. Will have access to the device after Monday.

**Comment by AmandaBekhoj** [comment]
hm, it is not better on my phone.. still not aligned

**Comment by mamont77** [comment]
Ok. Maybe it's better to hide for mobile devices? Until my iPhone does not come back.

**Comment by mamont77** [comment]
Ok. Maybe it's better to hide for mobile devices? Until my iPhone does not come back.

**Comment by AmandaBekhoj** [comment]
yes, that is fine :)

**Comment by AmandaBekhoj** [comment]
also, can vi resize the LinkedIn like button so it is the same size as the Facebook like button? :)
![skaermbillede 2015-02-03 kl 13 18 26](https://cloud.githubusercontent.com/assets/8081414/6020055/74ef459a-aba7-11e4-9a8c-c93018bdaf0c.png)

**Comment by mamont77** [comment]
FB and LinkedIn provides a ready code for the widget. Unfortunately, this can not be changed. ((
https://developers.facebook.com/docs/plugins/like-button
https://developer.linkedin.com/plugins/follow-company
Additionally buttons of different sizes. I searched the net for how to do it the same, but I don't found ((.

**Comment by AmandaBekhoj** [comment]
hm i understand. i just look a little weird that they have two different sizes. 

oh well. i will tell christian, it is he who does not like it. :)

**Comment by mamont77** [comment]
Reminder for me.
We can try: https://github.com/heiseonline/shariff + https://github.com/heiseonline/shariff-backend-php + http://fontawesome.io/icons/#brand.
Benefits. Fast loading pages (buttons). Single design and size of the buttons.
I will try this solution, when I have free time on the local version of the site.

**Comment by AmandaBekhoj** [comment]
would look good! but not good if there is no LinkedIn follow button :/

**Comment by mamont77** [comment]
Amanda,
What should I do in this task at this stage?

**Comment by AmandaBekhoj** [comment]
ignore it i think.. it is not particularly pretty, but it seems like it would be very time consuming to change it. 

maybe we will take it up at a later stage. :)
