### ISSUE TITLE
New menu tap

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#125]
So, we are going to create a new menu tap. 

I already created the page, but have not published it yet. 
It is called 'For Kandidater' 
and, it should be 'closed' as the rest of the menu taps. 

i need the 'tag kandidattest' page to be available through the menu tap, and i could not seem to do that?

*There was a paragraph. copied there #126*

does all of this make any sense?

**Comment by mamont77** [comment]
Please check now.
It would be very cool if we could remove the red round button. It looks bad, in my opinion.

**Comment by AmandaBekhoj** [comment]
very nice!

hm, we kind of like the red button ;)
