### ISSUE TITLE
Job page refactoring

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#126]
*Copied from #125.*

also, we need to make all the jobs visible on this site, BUT without the reward fee (like the one on salestribe.dk). so, there need to be a page called 'Jobs' where, for starters, all the jobs should be - but still in two grids. so there will be a grid for Salgsstillinger and a grid for Teknikstillinger (but on the same page). then it should be possible to press the job position and apply or send to a fried (as it is today for non-advisors)

**Comment by mamont77** [comment]
How to deal with forms that in the left sidebar. These should remain as it is. These different logic (fieldsets) for adviser and the anonymous user.

**Comment by AmandaBekhoj** [comment]
yes, they should remain as they are (as they are for anonymous user)

the adviser is still the only one to refer a candidate :)

**Comment by mamont77** [comment]
Amanda, please test it.
http://www.skillspeople.dk/jobs
This link is not in the menu. Except us, no one knows about the existence of this page.
If everything works as you want, we can add this page to navigate and delete old pages (version of views).

**Comment by mamont77** [comment]
I think we can delete "Jobs" title.
Because a lot of empty space.

**Comment by AmandaBekhoj** [comment]
you are right, we can delete the 'jobs' title :)

but, the 'henvis en candidate' won't be there, right? (since the candidates won't be logged in)

![skaermbillede 2015-01-23 kl 17 41 43](https://cloud.githubusercontent.com/assets/8081414/5878460/58a5ceaa-a327-11e4-8d63-f26d37ed0110.png)

it looks exactly as i imagined, i will just have to ask christian on monday what he thinks :)

**Comment by mamont77** [comment]
I can add "henvis en candidate" form to "job" page. Not a problem.

**Comment by mamont77** [comment]
Coincidence. A friend brought me a beer from Denmark.
I will be on Monday.
Amanda, Have a good evening))

**Comment by AmandaBekhoj** [comment]
noon it is good! the 'henvis candidate' should not be there :)
only the 'Søg stillingen' and 'del med fit network' 

NICE, how did you like the beer? :D 
Have a good weekend!

**Comment by mamont77** [comment]
I checked.
All three blocks uses of data from one job.
2
![1](https://cloud.githubusercontent.com/assets/970967/5887336/0b205414-a3d3-11e4-88ef-f792108714a0.png)
3
![2](https://cloud.githubusercontent.com/assets/970967/5887337/10b5be64-a3d3-11e4-9d43-3bb03ec04718.png)

So we can not use these blocks on this skillspeople.dk/jobs page.

Another way to create three tasks, there describes the behavior of these new forms. I can build similar. The new forms will not use the data from job entity.

This makes any sense?

P.S.: The name of the beer is "FAXE". Frankly, beer as beer. I like Ukrainian.

**Comment by AmandaBekhoj** [comment]
hm, i am a little confused. 

i just need the jobs on the new job page look like this: 

![skaermbillede 2015-01-24 kl 14 56 22](https://cloud.githubusercontent.com/assets/8081414/5887585/693ec426-a3d9-11e4-9a3c-ab4fd8e833b0.png)

(ofcourse, the 'søg stillingen' should not be extended by default :) )

**Comment by mamont77** [comment]
I'm a little confused also.

Step by step!
![skillspeople - referral recruitment kobenhavn - google chrome 01-24-2015 17 17 33](https://cloud.githubusercontent.com/assets/970967/5890588/fdf05580-a46a-11e4-8744-31fc7821a359.png)

**Job entity** http://www.skillspeople.dk/job/key-account-manager-glostrup-nianet
This page is not changed. I did not change anything here. It looks like it was before for the advisor and guest.
Similar pages have a form on the left sidebar.

**Job listing / views (the old/current version)** http://www.skillspeople.dk/ledige-stillinger-salg + http://www.skillspeople.dk/ledige-stillinger-teknik
These 2 pages haven't  any form on the left.

**Job (the new version)** http://www.skillspeople.dk/jobs
Currently there are no forms to the left.
If I understand correctly, you want to add two forms.

**What do these forms?**

**Henvis Kandidat!**
Sends (export) the form data to Podio, where there is a mandatory hidden field called "PodioJobID".
This value is in the material, when you add a new job. And Drupal can get this value when the visitor is on the page of a particular job.
Drupal does not know what value to use when the user is on this http://www.skillspeople.dk/jobs page.

**Søg stillingen**
Sends data to an email.
The field "Job title" is a mandatory.

**Del med dit netværk**
Sends the contents of the page (one job entity) to email.

**Conclusion**
To be able to use any form we have to modified these.
Add a new drop-down list field named as "Vælg stilling der henvises til" or "Select a job".

Such works on this http://www.skillspeople.dk/henvis-potentiel-kandidat page.
![henvis potentiel kandidat skillspeople - referral recruitment 01-25-2015 08 18 51](https://cloud.githubusercontent.com/assets/970967/5890595/63f2168e-a46b-11e4-939e-ed5ca6a359b7.png)

I understood you correctly?

**Comment by AmandaBekhoj** [comment]
Hehe i think we are confusing each other. i do not want forms on the http://www.skillspeople.dk/jobs  

i just wanted to make sure, that it was NOT possible anywhere to 'Henvis Kandidat' (refer candidate)

So, actually, everything is good! sorry for confusing!

**Comment by mamont77** [comment]
Amanda,

The title "Job page refactoring #126".
so I was always sure that talking about /jobs ;-)

Ok)))

**Comment by AmandaBekhoj** [comment]
heheh i was! but i just wanted to make sure, that it was not possible for guests to refer a candidate. and that was how i confused everyone!


but it seems like, this site is working fine. however, i just talked to christian, and this should not be directly accessible. but i will make a new issue now.

**Comment by AmandaBekhoj** [comment]
so, just keep this in testing for a little while, i will know soon what to do with it.

**Comment by AmandaBekhoj** [comment]
can you publish this now, so everyone can see it?

But when the search-interface is ready, this will need to be pulled back.

**Comment by mamont77** [comment]
Amanda, you can add the menu item "Jobs" and path "jobs".
Can you do it yourself?
Also need to remove or hide the old links.
After that, write me, I will deactivated the old "LEDIGE STILLINGER" pages.

**Comment by AmandaBekhoj** [comment]
i am not quite sure, what you mean? 
i cannot find the place where i can edit?
![skaermbillede 2015-01-29 kl 10 03 40](https://cloud.githubusercontent.com/assets/8081414/5954998/6577f132-a79e-11e4-9844-2078679a5892.png)

there is one site now, called 'Ledige stillinger' part of the 'Om os' and that is a person we are hiring, it should therefore stay.

**Comment by mamont77** [comment]
this a views, so doesn't node (content).
Done.
http://www.skillspeople.dk/retningslinier
http://www.skillspeople.dk/admin/structure/menu/manage/menu-for-advisors/list

**Comment by mamont77** [comment]
You can set
"Show block for specific roles" on http://www.skillspeople.dk/admin/structure/block/manage/menu/menu-for-kandidater/configure

**Comment by AmandaBekhoj** [comment]
okay.. so, it looks like everything is as you wanted? how do i publish it?

**Comment by mamont77** [comment]
It publish already :-) or not?

**Comment by mamont77** [comment]
Of course  you can hide the "For Advisors" block on /jobs page.

**Comment by AmandaBekhoj** [comment]
what? now i am confused. 

it should be located here, and should be available for all
![skaermbillede 2015-01-29 kl 10 45 12](https://cloud.githubusercontent.com/assets/8081414/5955544/1e2236de-a7a4-11e4-87cb-83078481051a.png)

**Comment by mamont77** [comment]
Amanda, you have access do it.

**Done!**
Home » Administration » Structure » Menus » Main menu >> Add link

Result:
![skillspeople - referral recruitment kobenhavn - google chrome 01-29-2015 11 49 37](https://cloud.githubusercontent.com/assets/970967/5955599/3596b5d4-a7ad-11e4-8905-51a5eebb36ec.png)

and
![jobs skillspeople - referral recruitment kobenhavn - google c 01-29-2015 11 49 58](https://cloud.githubusercontent.com/assets/970967/5955602/3affd88e-a7ad-11e4-9db5-4cdd3101e8e4.png)

If anything is unclear, feel free to ask me.

**Comment by AmandaBekhoj** [comment]
yes, i do not understand why the 'For advisor' menu block is visible and not the 'for kandidat' block?

**Comment by mamont77** [comment]
Amanda, you manage the site. You decide which block is visible on a page. :-)
http://www.skillspeople.dk/admin/structure/block/manage/menu/menu-for-kandidater/configure
http://www.skillspeople.dk/admin/structure/block/manage/menu/menu-for-advisors/configure

Let me show
![for advisors block skillspeople - referral recruitment kobe 01-29-2015 12 00 32](https://cloud.githubusercontent.com/assets/970967/5955737/adacb450-a7ae-11e4-8c76-546fb7b21413.png)

**Comment by mamont77** [comment]
Sorry, i have to go to hospital. I'll be back in a couple of hours.

**Comment by AmandaBekhoj** [comment]
oh, i am sorry you need to go to the hospital! 

this does not haste. and i am sorry for not understanding. i have corrected the 'for advisor' block so it does not show. but that makes me more confused, because the 'for kandidat' block is not visible, even though it has exactly the same (for me) settings as 'for advisor' 

![skaermbillede 2015-01-29 kl 11 11 22](https://cloud.githubusercontent.com/assets/8081414/5955860/a927072a-a7a7-11e4-910f-e7ca0ff39918.png)
![skaermbillede 2015-01-29 kl 11 11 38](https://cloud.githubusercontent.com/assets/8081414/5955864/aff60150-a7a7-11e4-8b71-43e81c39041a.png)
I cannot see what i am missing?? sorry

**Comment by AmandaBekhoj** [comment]
and also, it should be aligned 
![skaermbillede 2015-01-29 kl 12 00 05](https://cloud.githubusercontent.com/assets/8081414/5956518/f8d29a9e-a7ae-11e4-9172-59271c37ac6e.png)

**Comment by mamont77** [comment]
My son is in the hospital. Food poisoning. At night, the ambulance came. ((
Therefore, some days I partially available.

>> this does not haste. and i am sorry for not understanding. i have corrected the 'for advisor' block so it does not show. but that makes me more confused, because the 'for kandidat' block is not visible, even though it has exactly the same (for me) settings as 'for advisor'

may be  because the 'for kandidat' block has "show only for visitor".

You can write here:
* block should be visible (list of pages or rules)
* for someone (roles)

I will correct in 5 minutes. ))

>>  and also, it should be aligned 

The table responsive. it automatically adjusts to the width of the screen. 
These are two different tables that do not know about each other's existence. 
I'll think of a way to fix it.

**Comment by AmandaBekhoj** [comment]
i am so sorry to hear that! i hope he will feel better soon.


i have typed in that the block should be visible for these pages (jobs and tag-kandidattest) and i have made the roles to 'not restricted to any roles' but it is still not visible :(

thanks for helping!

**Comment by mamont77** [comment]
Ah. Look at my fix.

1. I unchecked the page type
![for kandidater block skillspeople - referral recruitment ko 01-29-2015 15 50 51](https://cloud.githubusercontent.com/assets/970967/5958605/fffd1cd4-a7ce-11e4-9079-75990b0cb0df.png)

2. Caches cleared.
![performance skillspeople - referral recruitment kobenhavn - g 01-29-2015 15 48 18](https://cloud.githubusercontent.com/assets/970967/5958609/0c5722f4-a7cf-11e4-8f6f-280557d459ad.png)

looks good to me now

**Comment by AmandaBekhoj** [comment]
yea i does! thanks.

then it is just the alignment of the grids

**Comment by mamont77** [comment]
>>then it is just the alignment of the grids

Fixed.

**Comment by AmandaBekhoj** [comment]
perfect! thanks :D
