### ISSUE TITLE
job search interface

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#127]
at some point, we are going to get a lot more jobs, because we want to 'crawl' relevant jobs from other sites. so we need a job search interface. 

This is the site, that guests should arrive at, before they see jobs. 

the page should be called 'Ledige jobs' and should be available from the 'For Kandidater' tap. 

The Ledige job interface, should look something like this: 

![skaermbillede 2015-01-26 kl 12 12 08](https://cloud.githubusercontent.com/assets/8081414/5898938/eeecae72-a554-11e4-863c-6a9f498735e3.png)

look here how it works: http://www. it-jobbank.dk 

all should be centered.

we are going through a major transition in the coming weeks, and i need to find head and tail in the project :) 

We will get two different kinds of jobs - the ones we get directly from our customers and the ones we 'borrow' from other job sites, using a internet crawler.

**Comment by mamont77** [comment]
I got it. It is really possible to build using Drupal. But it is a real piece of work. What is the deadline it should be done? I will schedule a time for the task.

**Comment by AmandaBekhoj** [comment]
yes please do so :)

**Comment by mamont77** [comment]
In process.

**Comment by mamont77** [comment]
I have a few questions. 

1/ Do we need to implement advanced search?
![find dit it-job pa danmarks jobportal for it-folk it-jobbank 02-04-2015 11 40 02](https://cloud.githubusercontent.com/assets/970967/6038083/b320ce4a-ac62-11e4-89bb-16e44d2d036f.png)

2/ Do we need in additional blocks and filters as here?
![ledige job - software- webudvikling it-jobbank - google chro 02-04-2015 11 41 01](https://cloud.githubusercontent.com/assets/970967/6038109/02b5c4f6-ac63-11e4-9316-15c9d1303ff5.png)

**Comment by mamont77** [comment]
Also...
We have two categories:  Salg & Teknik. Perhaps the name "category" is not correct and it is better to say the "type of job".
However "JobBank" has more categories and sub categories.
 
![ledige job - software- webudvikling it-jobbank - google chro 02-04-2015 11 58 29](https://cloud.githubusercontent.com/assets/970967/6038404/6341a2a2-ac65-11e4-8271-27a365412613.png)

Will your site contain the same list or it be different? In this case, please provide a list of categories.
Perhaps we need to add new fields to the "Job Posting". I need a list of fields and their possible values.

After that, we are ready to start implementing the first phase of this task.

**Comment by AmandaBekhoj** [comment]
1. we need the 'Find job' search field, where people can search for something specific. 
and then we need the advanced search yes, The first should be job categories (the same categories as we have in the 'kandidattest') 
![skaermbillede 2015-02-04 kl 14 51 10](https://cloud.githubusercontent.com/assets/8081414/6041497/50c152c2-ac7d-11e4-97f9-ad04cb5da2ed.png)

and the second one should be according to places yes. also the same as we have on the kandidattest site. 
![skaermbillede 2015-02-04 kl 14 53 04](https://cloud.githubusercontent.com/assets/8081414/6041523/9093e4d2-ac7d-11e4-969e-4455d64bb807.png)

(we then need to make it possible to put these information to each job, in order to categorize them :) )

we do not have the one called 'virksomhedsoversigt' ..

2. yes i would say so, then it is easier for the visitor to navigate. but we only need the 'find job' search space, and not the 'hvor' ..
'dine valg' specifies which categories you have already chosen.. might not be relevant, if you can see which boxes you have ticked in 'område' (area/places) and 'job categories'

3. actaully, it would be fine if we called one category for 'IT-salg', and then the subcategories should be:
Salgsstillinger
Salgsledelse

and the second category should be 'Teknik' and the sub categories should be:
IT-tekniske stillinger
Udvikling/arkitekt
IT-sikkerhedsstillinger
IT-ledelse 

does this make sense?

**Comment by mamont77** [comment]
Amanda,

Please, check out these three links.
http://www.skillspeople.dk/admin/structure/taxonomy/job_categoty
http://www.skillspeople.dk/admin/structure/taxonomy/region
(you can rename the label - push "edit" tab)
http://www.skillspeople.dk/node/137/edit

'm not sure that I understood about 'virksomhedsoversigt'. So I added the word to a category.

If I did everything correctly, please update all the jobs.

Then, I think we can remove the old field category.
![edit job posting senior sales specialist - silkeborg - coresec s 02-04-2015 16 42 35](https://cloud.githubusercontent.com/assets/970967/6042384/ee4b234c-ac8c-11e4-8db6-682e13703f32.png)

**Comment by AmandaBekhoj** [comment]
Perfect, seems good!

i just deleted 'virksomhedsoversigt' it should not be anywhere :)

i will update all the jobs!

**Comment by AmandaBekhoj** [comment]
i have updated all jobs.. but i think it should be possible to choose more than one :) some of them could fit under more categories :) and also for the region - some of the companies are located more places :)

**Comment by mamont77** [comment]
ok. i will fix tomorow.

**Comment by mamont77** [comment]
>>it should be possible to choose more than one

Fixed.

1. Can we delete old category field?
```
Category *
 Salg
 Teknik
```
2. Can we show the category(es) and region(s) fields on job page for advisor or visitor?

**Comment by AmandaBekhoj** [comment]
1. yes i think you can
2. yes, please show the categories and regions on the left side of the job page (as on the it-jobbank site) but only for visitors

**Comment by mamont77** [comment]
1. deleted.

2. Amanda, I'll need about 2 hours to make the categories and regions in the left sidebar. Because the left sidebar does not know anything about the existence of the central content.
I suggest another. Can we make a business card for job? Look at screensnap.
![microsoft infrastruktur konsulent - kobenhavn - infrahouse ski 02-05-2015 15 42 17](https://cloud.githubusercontent.com/assets/970967/6061143/d05594fa-ad4d-11e4-987e-45c91ec44434.png)
We can change the design to make more beautiful. And increase the logo twice.

Why categories and regions should only be displayed for anonymous user? 
To do this, I need to install an additional module for Drupal.

**Comment by AmandaBekhoj** [comment]
it can be shown for everyone, that does not make any difference :)

hm. the thing is, that i like the way that it-jobbank does it, because it makes it possible for the visitor to quickly find jobs in another category or region.. and we should make it as easy for the visitor as possible :)

**Comment by mamont77** [comment]
It will be possible at the next stage, after we do the search for work and filters. At this stage it is just text. Can we temporarily leave as shown in the picture (it works on the site). Or go back as it was before?

**Comment by AmandaBekhoj** [comment]
okay perfect!

yes we can leave as it shown on the picture. :)

**Comment by AmandaBekhoj** [comment]
oh really?

i just made two images that have the same side as the rest of the icons

it is not possible to use one of them? 

![skaermbillede 2015-02-05 kl 15 23 53](https://cloud.githubusercontent.com/assets/8081414/6062060/10de74d4-ad4d-11e4-8f5e-c5b4185a9372.png)

![skaermbillede 2015-02-05 kl 15 35 46](https://cloud.githubusercontent.com/assets/8081414/6062062/164c33e8-ad4d-11e4-9e7c-8252e92f6674.png)


i do not know it it will be pretty.. it just have to make some sense for the visitor

**Comment by mamont77** [comment]
ok. we can try))

**Comment by AmandaBekhoj** [comment]
oh sorry, wrong issue!!

**Comment by mamont77** [comment]
@AmandaBekhoj,

This is a prototype of the pages. Visible only to the administrator. The design is not implemented yet.
At the moment I do not know how to implement the advanced search. But I think about it.

Overview page: http://www.skillspeople.dk/find-job
Search result page: http://www.skillspeople.dk/jobsoegning?key=Senior

Is it similar to what you want? Can we continue on? If it's less work as you like, I will continue to make beautiful designs.

**Comment by AmandaBekhoj** [comment]
wow it has come a long way!

so i have some notes. 
1. could the search field be bigger? both hight and width
2. it would be nice, if there was a text in the search field (which would disappear as soon as you started to write) that says 'Indsæt f.eks. titel, virksomhed og område' - in light grey. 
3. it would be nice to have our job categories listed under the search field, to give a clear indicator of, what people can find. and then a counter, saying how many jobs are available within each job category. link it-jobbank
![skaermbillede 2015-02-06 kl 15 53 37]
(https://cloud.githubusercontent.com/assets/8081414/6081260/88accb0c-ae18-11e4-94e3-152028f288f8.png)

4. the search result page is a bit messy and hard to figure out. so it would be nice if it could be designed as something similar to this, so there was a clear distinction from job to job, and where the logo belongs. 
![skaermbillede 2015-02-06 kl 15 56 53](https://cloud.githubusercontent.com/assets/8081414/6081311/e72b16fc-ae18-11e4-823e-8d20c562ee43.png)

but so far so good :D

**Comment by mamont77** [comment]
ll your comments about the design and the advanced search. )) 
Well, as I understand it, we are on the right way.

**Comment by AmandaBekhoj** [comment]
yes :)

**Comment by mamont77** [comment]
Amanda, i have one question about it-jobbank's "avanceret søgning" block.
It seems display category only. Without subcategories.
We have 2 category only. Teknik && IT-salg.
What should we display in our case? Because I do a prototype of advanced search.
http://www.skillspeople.dk/find-job

**Comment by AmandaBekhoj** [comment]
IT-jobbank are only displaying the job categories with the most jobs on their front page. 
![skaermbillede 2015-02-06 kl 16 41 33](https://cloud.githubusercontent.com/assets/8081414/6082139/23086552-ae1f-11e4-8c59-8146de08e050.png)
same as 
![skaermbillede 2015-02-06 kl 16 41 42](https://cloud.githubusercontent.com/assets/8081414/6082146/331838be-ae1f-11e4-84ee-4b3b2822e77b.png)

but all they are doing, actually, is pairing the job categories with regions, in order to be more specific. 
so that is all we should do as well. for now. 

and i know we do not have as many job categories, but hopefully we will get more, and then the advanced search will seem more advanced. 

right now, advanced search should pair a job category with a region.

**Comment by mamont77** [comment]
Amanda,
please review that page only http://www.skillspeople.dk/jobsoegning

That page http://www.skillspeople.dk/find-job in process still. And in my opinion, this page is not necessary.

**Comment by AmandaBekhoj** [comment]
i think it looks really nice! good job! 

but i get this box often, when i try to navigate around

![skaermbillede 2015-02-09 kl 11 42 44](https://cloud.githubusercontent.com/assets/8081414/6104781/dc2fc1e6-b050-11e4-8a62-e0b7c4d5689b.png)

you are right, we do not need /find-job as an entire page, but we do need the block somewhere on the /jobsoegning page..

**Comment by mamont77** [comment]
Amanda,
Can you install: firefox, chrome, team viewer?
And ping me in skype.
I have to find the reason of bug. It takes about 20 minutes.

**Comment by AmandaBekhoj** [comment]
i am sorry, i am actually not working today, because my dad is visiting from bangkok! can we do it on wednesday when i am back at the office?

**Comment by mamont77** [comment]
yes of course)) Have a nice day))

**Comment by mamont77** [comment]
Current result:
![find job skillspeople - referral recruitment kobenhavn - goog 02-09-2015 18 02 50](https://cloud.githubusercontent.com/assets/970967/6109786/05e07b18-b086-11e4-90a8-765f95ff8351.png)

**Comment by AmandaBekhoj** [comment]
this looks really good! but look at my comment for #135 , i think this also applies here

**Comment by AmandaBekhoj** [comment]
so, christian would like to hear if we could make the search field 25% thinner?

also, the colors are not exactly right. 

the 'find job' should have color #44C7F5 and the 'søg' button should have color #5CB1D3

**Comment by mamont77** [comment]
Done.

Before
![find job skillspeople - referral recruitment kobenhavn - goog 02-11-2015 14 09 13](https://cloud.githubusercontent.com/assets/970967/6146639/a7a27830-b1f7-11e4-8e1b-315824886ed0.png)

After
![find job skillspeople - referral recruitment kobenhavn - goog 02-11-2015 14 09 29](https://cloud.githubusercontent.com/assets/970967/6146644/af20f5fa-b1f7-11e4-9e77-7bc2b971354b.png)

I also want to draw your attention to how it looks for the mobile version. Perhaps, too, it is necessary to change the size and color.
![screensnap - infrahouse - find job skillspeople - referral rec 02-11-2015 14 11 23](https://cloud.githubusercontent.com/assets/970967/6146674/ea0fcf88-b1f7-11e4-9756-8a9a86008808.png)

**Comment by AmandaBekhoj** [comment]
perfect! you are right with the mobile device! that would be best :)

**Comment by AmandaBekhoj** [comment]
so, i guess it should be published now? instead of the http://www.skillspeople.dk/jobs page. :)

but, i have added most of the jobs (with the short title and contact information) and i have changed the categories, but it is not changed on the http://www.skillspeople.dk/jobsoegning ?
![skaermbillede 2015-02-12 kl 10 25 49](https://cloud.githubusercontent.com/assets/8081414/6164750/3bfbe1a6-b2a2-11e4-8607-51184cac5cd7.png)

and then the task #132 should be done :)

**Comment by mamont77** [comment]
And So.
1. now block "Populære job" uses short title (http://www.skillspeople.dk/jobsoegning)
2.  block "Populære job" on front page uses short title also.
3. I added left block/menu "For kandidater" on http://www.skillspeople.dk/jobsoegning and you can remove this block if need.
4. Category names look good to me. Perhaps as a result of changes in the categories - broken category in some jobs. In this case you must check the category in all the jobs. Look at image:
![content skillspeople - referral recruitment kobenhavn - googl 02-12-2015 14 18 07](https://cloud.githubusercontent.com/assets/970967/6167312/a55ab1c0-b2c2-11e4-8cac-f2b380bd4003.png)

>>i guess it should be published now? instead of the http://www.skillspeople.dk/jobs page. :)

Done.

Can we delete old page? http://www.skillspeople.dk/jobs
This page http://www.skillspeople.dk/find-job I still need some time, then I will remove it too.

**Comment by AmandaBekhoj** [comment]
perfect!

it looks like some of the categories are missing though??

**Comment by mamont77** [comment]
Maybe there is not a one job with this category?

**Comment by AmandaBekhoj** [comment]
aaah yes of course! sorry :)

**Comment by mamont77** [comment]
Can we close this issue?

**Comment by AmandaBekhoj** [comment]
yes in theory. but the site does not look good on mobile devices. should i make a new issue for this?

but - on the mobile, the categories comes first, and then the 'populære jobs' and this is not good. the search function should be the first thing to see, and then jobs we have (search results when people search for something) 

actually, the 'categories' and 'region' section does not have to be there.. and 'populære jobs' should be placed last on the site. 

does this make sense? :))

**Comment by mamont77** [comment]
I think functional works and we can close. There are a lot of messages.
You can create a new task for mobile.

Page built from the top down and from left to right, for any device. Look at attachment.
![find job skillspeople - referral recruitment kobenhavn - goog 02-16-2015 11 17 18](https://cloud.githubusercontent.com/assets/970967/6209342/9614e9d4-b5cd-11e4-91a2-5b445aa835c1.png)
Maybe it's a bad idea.

There is another way.
We can try uses module like that https://www.drupal.org/project/mobile_detect
And move blocks to the right for mobile devices only.

But this functionality is not related to search functionality, so I created another task (#147).

**Comment by AmandaBekhoj** [comment]
i think your second idea is best. - move the block to the right for mobile devices only. 

so i should close this, issue?
