### ISSUE TITLE
Menu on the jobs pages

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#128]
So i wanted to add menu's on the individual jobs pages, in order to make it possible for guests to navigate easier around. like this:
![skaermbillede 2015-01-27 kl 15 55 52](https://cloud.githubusercontent.com/assets/8081414/5920512/5ed2a690-a63d-11e4-9cc6-5c4b000f55ba.png)

but the menu won't show! i created it in structure --> menu --> ledige stillinger salg, and ledige stillinger teknik.

and i also made sure to add the path in the blocks?

but it still does not show. what is wrong?

![skaermbillede 2015-01-27 kl 15 17 17](https://cloud.githubusercontent.com/assets/8081414/5920542/a3112124-a63d-11e4-9074-0c497b42d0e4.png)

OBS: this is only for the jobs available for advisors.

**Comment by mamont77** [comment]
You created a menu, now you want to display the menu in the block.

Next step!
Please go to http://www.skillspeople.dk/admin/structure/block
1. Set for "Ledige stillinger salg" and "ledige stillinger teknik" the "First Sidebar" region.
2. Edit to blocks, set "Content types" = Job Posting, set "Roles" = anonymous user.

**Comment by mamont77** [comment]
Can you to do it? ))

**Comment by AmandaBekhoj** [comment]
i did exactly what you directed, but the menu has not appeared? :(

**Comment by mamont77** [comment]
I can see:
Show block on specific pages
Only the listed pages
sharepoint-account-manager-koebenhavn-innofactor
account-managers-soborg-kompetera
salgsleder-er-glostrup-rahmqvist
BUT
http://www.skillspeople.dk/salgsleder-er-glostrup-rahmqvist
Side ikke fundet
Siden "/salgsleder-er-glostrup-rahmqvist" findes ikke.

I deleted the wrong aliases.
It works now.
But you can add right aliases like "node/125" - permanent id - if you change the name or alias, permanent link remain unchanged.

or
job/sharepoint-account-manager-koebenhavn-innofactor
job/account-managers-soborg-kompetera
job/salgsleder-er-glostrup-rahmqvist

and
job/microsoft-infrastruktur-konsulent-koebenhavn-infrahouse
job/projektlederproces-implementeringskonsulent-kobenhavn-infrahouse
job/senior-bidw-arkitekt-ballerup-sdc
job/it-sikkerhedskonsulent-herlev-ezenta
job/senior-it-security-consultantcheck-point-silkeborg-ezenta
job/program-managerprojekt-leder-hellerup-saxo-bank
job/sharepoint-team-lead-koebenhavn-innofactor
job/sharepointnintex-konsulent-koebenhavn
job/microsoft-sam-specialist-kobenhavn-crayon
job/sharepointkonsulenter-koebenhavn-aarhus-innofactor

In this case it will be an additional check and blocks the menu will be visible only on selected pages (not for all jobs).

**Comment by mamont77** [comment]
You manually create these menus. Alternatively, we (I) can make a views that automatically displays all the published jobs without exception. In this case, you do not have to worry about these menus.
It will use the same principle as the home page.

**Comment by AmandaBekhoj** [comment]
you can do that?? that would be perfect! since we delete and add jobs often!

**Comment by AmandaBekhoj** [comment]
hm, not it is the 'for advisor' menu block that is shown? why is it so annoying!!!

**Comment by mamont77** [comment]
With some (or any) of the page ш should to delete  'for advisor' block?

**Comment by mamont77** [comment]
Amanda,
I deleted the two menus and blocks.
Instead I created views and blocks.
Now you do not have to worry about the menu, the links will always relevant.
Please check it.

**Comment by AmandaBekhoj** [comment]
there is still no menu? :(
![skaermbillede 2015-01-30 kl 11 01 26](https://cloud.githubusercontent.com/assets/8081414/5974008/77b2e682-a86f-11e4-85e8-635662d84470.png)

**Comment by mamont77** [comment]
Amanda,
These blocks are only visible for anonymous role!
![microsoft infrastruktur konsulent - kobenhavn - infrahouse ski 01-30-2015 12 05 43](https://cloud.githubusercontent.com/assets/970967/5974045/7091001a-a878-11e4-8468-06614c39a37b.png)

You can remove "Show block for specific roles" checkbox for anonymous here:
http://www.skillspeople.dk/admin/structure/block/manage/views/job_posting_v2-block_3/configure
http://www.skillspeople.dk/admin/structure/block/manage/views/job_posting_v2-block_4/configure

**Comment by AmandaBekhoj** [comment]
aaaaah..

they should be available for everyone :) sorry!

**Comment by mamont77** [comment]
Can you fix?

**Comment by AmandaBekhoj** [comment]
WUHUUU i fixed something! :D thanks

**Comment by mamont77** [comment]
>>WUHUUU 

Respect :-D
