### ISSUE TITLE
Tag Candidat Test issue on mobile device

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#130]
![screenshot_2015-01-28-20-32-18](https://cloud.githubusercontent.com/assets/970967/5944269/3e0761fc-a72e-11e4-8385-a32e81411d82.png)

**Comment by AmandaBekhoj** [comment]
ah yes, not good. can u fix?

**Comment by AmandaBekhoj** [comment]
i think this issue is solved, yes?

**Comment by mamont77** [comment]
not yet. This only happens in one browser. FF, Chrome works fine. I will investigate it when I finish other tasks.

**Comment by mamont77** [comment]
Fixed. Ready for testing if possible :-)

**Comment by AmandaBekhoj** [comment]
i get the same AJAX HTTP message when i try to upload through mobile device :(

**Comment by mamont77** [comment]
This issue about big red btn only. I see your comment in #141. Checking.

**Comment by AmandaBekhoj** [comment]
ah okay, then it works :)
