### ISSUE TITLE
problems with the kandidattest-link

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#131]
Hi Ruslan

Some of our candidates have trouble with the test link, and says that it does not open for them, which is not good. 

but since it is not a pop-up, that can not be the problem right?

also, if they have already submitted information and CV, but the test did not pop up (of if they close the new tap by accident), then it is not possible to re-submit information and CV.. it will not give access to the test link. 

this is not good :(

**Comment by mamont77** [comment]
I found the reason.
![tag kandidattest skillspeople - referral recruitment kobenhav 02-05-2015 14 34 26](https://cloud.githubusercontent.com/assets/970967/6060352/af9a4548-ad44-11e4-9eff-5f0b10f03e12.png)
So I added a link back. But now it does not open in a new window (same).
I think we can make a beautiful button and ask the candidate to click on it.
What do you think about this?

**Comment by mamont77** [comment]
What do you think about this solution?
You can try.
![tag kandidattest skillspeople - referral recruitment kobenhav 02-05-2015 14 51 01](https://cloud.githubusercontent.com/assets/970967/6060526/9a33fcd8-ad46-11e4-9295-57fbe825a818.png)
No JS popups. Works in any browser.
You can change text at btn here: http://www.skillspeople.dk/node/134/webform/configure.

**Comment by AmandaBekhoj** [comment]
I think this is a good solution, and a beautiful button! lets do that :)

**Comment by mamont77** [comment]
Done)) Please update "Teke Test" link )) http://www.skillspeople.dk/node/134/webform/configure.

**Comment by AmandaBekhoj** [comment]
much better!

but is still acting a little weird. when i press 'send ind' it just go to the top of the page.. and then i need to press 'send ind' again .. it should work in the first klick :)

**Comment by mamont77** [comment]
it works in the first click to me :) can you show in any way?

**Comment by AmandaBekhoj** [comment]
i have sent you an email with a video where i show you

**Comment by mamont77** [comment]
This is the strangest thing I've seen in recent years. I will try to understand what caused this problem. If possible, try using a different (other) computer or browser. Maybe it will help me.

**Comment by AmandaBekhoj** [comment]
yes i know, it is very strange! 

i just took it through my firefox browser, and it worked fine. 

but then i tried to log out, and take it on safari, and then this came up when i tried to submit my CV?
![skaermbillede 2015-02-05 kl 14 38 01](https://cloud.githubusercontent.com/assets/8081414/6061094/d66d6718-ad44-11e4-867b-ba102b52f316.png)

**Comment by mamont77** [comment]
I investigate. ((

**Comment by mamont77** [comment]
Try to force reload the page or clear the browser cache in another way. I hope this helps.

**Comment by mamont77** [comment]
I think we can close and continue in #141.

**Comment by AmandaBekhoj** [comment]
perfect :)
