### ISSUE TITLE
edit of third top block 

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#133]
There are four top blocks (advisor netwærk, passiv rekruttering, salestribe, and the job slider)

![skaermbillede 2015-02-05 kl 13 59 26](https://cloud.githubusercontent.com/assets/8081414/6060898/b484f0aa-ad42-11e4-8dab-1088d5ae53df.png)

Do you think it is possible to, edit the image of the third top block (salestribe) to the thumbnail of a movie that we have made? and then make it possible to press on the thumbnail, and then get the video to pop, as it does on infrahouse?
![skaermbillede 2015-02-05 kl 14 16 25](https://cloud.githubusercontent.com/assets/8081414/6060902/bc984990-ad42-11e4-9922-0871ae954b41.png)

this is the link to the video https://www.youtube.com/watch?v=ldvKai5VCvA 

i hope this makes sense :))

**Comment by mamont77** [comment]
it is possible :stuck_out_tongue_winking_eye:
Today you write a lot, I was confused.

I understand everything about the video.
One question.  Do you want to install a different icon instead of an Indian Apache? Do you have this icon?

**Comment by AmandaBekhoj** [comment]
hehe sorry. i hope you a not too confused anymore. 

yes, it should be another image than the indian apache. 

this is a snapshot from the video. so it would be appropriate to have it resized to fit, and then this should be the thing to click on :)

![skaermbillede 2015-02-05 kl 15 23 53](https://cloud.githubusercontent.com/assets/8081414/6061807/2b14c5da-ad4b-11e4-855c-8e991998b3b5.png)

you want me to send in an email?

**Comment by mamont77** [comment]
I'm afraid I did not do it beautifully. I am not an artist. And not a designer. I can not make an icon using  the photo.Need to find a ready icon or seek a talented designer.

**Comment by AmandaBekhoj** [comment]
i appreciate the effort!

it is not possible just to resize it? like the thumbnail on of a Facebook profile picture?

or else, we will take a movie-icon

**Comment by mamont77** [comment]
Of course we can replace the icon by photo. But it will be very different from the neighboring icons. I do not think it will be beautiful. What do you think about this?

**Comment by mamont77** [comment]
It is necessary to remove the window and the background. and make like http://fc09.deviantart.net/fs70/i/2012/065/4/5/bruce_lee_the_legend_sketch_portrait_by_wulfwood04-d4rw1ap.jpg

**Comment by AmandaBekhoj** [comment]
sorry for posting pictures in the wrong issue!

**Comment by mamont77** [comment]
Amanda, please test a new block.
Attention, this block is only visible to the administrator role. Other users can not see it.
![skillspeople - referral recruitment kobenhavn - google chrome 02-06-2015 09 11 50](https://cloud.githubusercontent.com/assets/970967/6075690/5574a9c2-ade0-11e4-9753-2c1964f4db79.png)

**Comment by mamont77** [comment]
Added second version with hover effect.
![skillspeople - referral recruitment kobenhavn - google chrome 02-06-2015 10 24 35](https://cloud.githubusercontent.com/assets/970967/6076311/8bc8330e-adea-11e4-8fe9-13880cb0c983.png)

**Comment by AmandaBekhoj** [comment]
wow i think looks great! i like the one with hoover effect! and it works really good with the video!

is it possible for me to change the change the video, when we create new videos? and also the image/thumbnail?

**Comment by mamont77** [comment]
>>is it possible for me to change the change the video

Not a problem.
![videoblog v2 block skillspeople - referral recruitment kobe 02-06-2015 11 23 30](https://cloud.githubusercontent.com/assets/970967/6076960/c6fef1bc-adf2-11e4-992c-c724c062d343.png)

>>also the image/thumbnail?

Unfortunately it is sewn in the design. You can change the picture, but will lose the hover effect. I can give you instructions on how to do this, but I'm afraid you will break sooner or later.  I think better to find a universal icon.

Can you set the new version and delete the old?

**Comment by AmandaBekhoj** [comment]
as long as i can change the video, it is fine. i need to get feedback from christian before i delete and set the new. :)

**Comment by mamont77** [comment]
And probably the visitor must have the gift of extrasensory to click on the icon. ;-) It's more like an Easter egg.

**Comment by AmandaBekhoj** [comment]
hahah i know! but it says in the text, that they should click it ;)

**Comment by mamont77** [comment]
ah -D I have not learned Danish yet.

**Comment by AmandaBekhoj** [comment]
it should be on your to-do list! :D

**Comment by mamont77** [comment]
In this case, you will be my teacher :-P

**Comment by AmandaBekhoj** [comment]
of course! luckily for you, google translate has also become quite good ;)

**Comment by mamont77** [comment]
))

**Comment by AmandaBekhoj** [comment]
christian liked the hoover version, so you can implement it :)

**Comment by mamont77** [comment]
Can you set the new version and delete the old? ))

**Comment by AmandaBekhoj** [comment]
yeees, i did it :D

**Comment by mamont77** [comment]
Excellent!
