### ISSUE TITLE
the forth top block - job slider

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#135]
The fourth top block where our jobs are sliding through - christian would like it to be changed. we would like it to be like it to be a grid, like the one we already have. but it should be in the same font size as the  rest of the top blocks of course. 

![skaermbillede 2015-02-05 kl 14 47 27](https://cloud.githubusercontent.com/assets/8081414/6061216/11a9fc0a-ad46-11e4-804e-eb1286fc211a.png)

there should be no destination between what type of job it is. 

the logo should be visible (small) and then the job position and job location, and company. 

lastly, all the jobs cannot be there at once, so the grid should be 'rolling' so there will be coming a new job down from above, and the last job will 'roll out' 

does this make sense? :)) it is hard for me to explain this sort of thing

**Comment by AmandaBekhoj** [comment]
it should be possible to click your way to the job posted :) 

maybe it is okay to only have the logo and job position.. am not sure it looks good with all the other information

**Comment by mamont77** [comment]
Can we use as idea block from http://www.skillspeople.dk/find-job?

**Comment by AmandaBekhoj** [comment]
yes :)

**Comment by mamont77** [comment]
Amanda, please review.
At the moment, this unit is visible for administrator role only.
![skillspeople - referral recruitment kobenhavn - google chrome 02-07-2015 13 05 54](https://cloud.githubusercontent.com/assets/970967/6091881/506c0214-aeca-11e4-8344-58e54c6a7122.png)

**Comment by AmandaBekhoj** [comment]
hm.. it does not look so good right? because of all the text. maybe it should just be the logo and the job title..

like this

![skaermbillede 2015-02-09 kl 11 03 34](https://cloud.githubusercontent.com/assets/8081414/6104308/8ed68d3e-b04c-11e4-9c7a-9bfc90430ca6.png)

but then there need to be a field where i only write the job position. 
Also, the logo could be smaller.. there is not much room in the fourth top block :)

**Comment by mamont77** [comment]
Amanda,
Please check new version on Wednesday.
![skillspeople - referral recruitment kobenhavn - google chrome 02-09-2015 17 48 19](https://cloud.githubusercontent.com/assets/970967/6109518/f41d25c2-b083-11e4-8df0-b6ac99bad7b6.png)

I did not add a new "Short Title" field.
The main title trimmed to a maximum length (45) and added an ellipsis.

**Comment by AmandaBekhoj** [comment]
hm don't you think it will be better, if there where a new short title field? i think this looks a little messy.. also on the job search site. it would be much better if there was only one the job title

**Comment by mamont77** [comment]
I created one new field called "Short Title".
Ex: http://www.skillspeople.dk/node/98/edit
1. Amanda, please update all jobs. Because I can not write data about manager.
2. Then write me and we will try to use the new field.
3. Champagne.

**Comment by AmandaBekhoj** [comment]
i look forward to 3. 

i will update all managers tomorrow when i get the names from christian, and then i will also update the jobs. :))

**Comment by mamont77** [comment]
ok))

![1389618268_1766809](https://cloud.githubusercontent.com/assets/970967/6127200/0dd56562-b131-11e4-8fe8-64a2ae5fccd7.jpeg)

**Comment by mamont77** [comment]
Please review again.

**Comment by AmandaBekhoj** [comment]
if it looks like it does on the /find-job page, then it is good :)

it was not changed in the link in this issue

**Comment by AmandaBekhoj** [comment]
sorry i looked the wrong place! it looks very good :))) i will remove the old fourth top block :)
can?

**Comment by mamont77** [comment]
>>can?

yes)) and publish a new block for all roles (for admin now).

**Comment by AmandaBekhoj** [comment]
hm, for some reason, i cannot delete the old fourth top block?
![skaermbillede 2015-02-12 kl 15 52 28](https://cloud.githubusercontent.com/assets/8081414/6169645/43d982de-b2cf-11e4-8b5c-4b4f71dbcff2.png)

**Comment by mamont77** [comment]
set region "none" ))  is a program block, it can only hide.

**Comment by AmandaBekhoj** [comment]
okay, thanks!

but, i just saw that it looks like this, maybe it can be aligned with the other blocks? 
![skaermbillede 2015-02-12 kl 15 55 08](https://cloud.githubusercontent.com/assets/8081414/6169710/ad7959da-b2cf-11e4-82b0-1a73ae0f798a.png)

**Comment by mamont77** [comment]
Can you revert back? I'll do a little bit later.

**Comment by mamont77** [comment]
i reverted back

**Comment by mamont77** [comment]
Fixed.
Result:
![skillspeople - referral recruitment kobenhavn - google chrome 02-12-2015 18 02 38](https://cloud.githubusercontent.com/assets/970967/6171067/692680de-b2e1-11e4-9ffa-2c2615c0c8dd.png)

Please check.

**Comment by AmandaBekhoj** [comment]
much better! thanks :))
