### ISSUE TITLE
More information when adding a job 

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#138]
So, with the new direction we are taking, we need to add some more information, when we add a job. 

it should be called 
- Hiring managers' navn (name)
- Hiring Managers' telefon (phone)
- Hiring managers email 

This information should also be available to the viewers of the job (both advisors and anonymous) 
but is should be presented differently. 

i like the box you have made with the logo, job category and region. and i was thinking there could be one more box underneath, that says 'Kontakt' and then the name, phone and email. 

![skaermbillede 2015-02-06 kl 16 18 01](https://cloud.githubusercontent.com/assets/8081414/6081913/46b76a4a-ae1d-11e4-8783-79e59e9c3b3d.png)

this makes sense?

**Comment by mamont77** [comment]
Amanda,

Done. Please review.
![senior bi dw arkitekt - ballerup - sdc skillspeople - referral 02-07-2015 12 23 46](https://cloud.githubusercontent.com/assets/970967/6091768/5b194ef2-aec4-11e4-9c0d-9946480ce637.png)

**Comment by AmandaBekhoj** [comment]
It looks good! however, the only the name, phone number, and email should be visible to the viewer :) not the 'hiring managers name, hiring managers telefon, and hiring managers email' 

but it looks very good!

**Comment by mamont77** [comment]
Fixed. Please update all jobs.

**Comment by AmandaBekhoj** [comment]
thanks!

**Comment by mamont77** [comment]
![senior sales specialist - silkeborg - coresec systems a s skil 02-12-2015 13 45 33](https://cloud.githubusercontent.com/assets/970967/6167635/0d1788a8-b2c6-11e4-860a-d4f7c6f950f4.png)
![sharepointkonsulenter - kobenhavn arhus - innofactor a s ski 02-12-2015 14 48 14](https://cloud.githubusercontent.com/assets/970967/6167651/39e87496-b2c6-11e4-9958-ca196ca705e4.png)

![sharepointkonsulenter - kobenhavn arhus - innofactor a s ski 02-12-2015 14 50 34](https://cloud.githubusercontent.com/assets/970967/6167682/9762d738-b2c6-11e4-9413-0ed5f21a8692.png)

Amanda, I do not like when the block is too wide. Can we limit the maximum width and add the word wrap?

**Comment by AmandaBekhoj** [comment]
i agree, and christian and me talked about it. but we did not know what could be done.. 

yes i guess a maximum width is a good idea, but how will that interfere with the email?
i do not know what truncate means?

**Comment by mamont77** [comment]
Like that
![senior sales specialist - silkeborg - coresec systems a s skil 02-12-2015 15 01 40](https://cloud.githubusercontent.com/assets/970967/6167820/1b537402-b2c8-11e4-99fd-7ecb79c2495a.png)

**Comment by AmandaBekhoj** [comment]
yea, i think this is better!

**Comment by mamont77** [comment]
I did not do it yet.

**Comment by AmandaBekhoj** [comment]
oh sorry :)

**Comment by mamont77** [comment]
Fixed.
Please review.
Result:
![senior sales specialist - silkeborg - coresec systems a s skil 02-12-2015 15 30 35](https://cloud.githubusercontent.com/assets/970967/6168264/473431ca-b2cc-11e4-8e5e-bb2e4d2a4373.png)

**Comment by AmandaBekhoj** [comment]
good, much better :)
