### ISSUE TITLE
apply for job function

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#139]
Right now, when people apply for a job, we are the only ones that get the application and CV, but we would like for the hiring manager to get it as well. 

therefore this issue is dependent on #138 

so, both us and the hiring manager will receive the application on email :)

**Comment by mamont77** [comment]
Done.
Result:
![website apply job posting request podio id 0f9cf6e00c - rusla 02-09-2015 18 47 51](https://cloud.githubusercontent.com/assets/970967/6110735/68a8141c-b08c-11e4-9643-804569a7b773.png)

**Comment by AmandaBekhoj** [comment]
very good! :D
