### ISSUE TITLE
email to people who apply

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#140]
We would also like for people who apply for a job to receive an email saying: 

'Hej [applicants name] (stated in drupal when applying)
Mange tak for din ansøgning til stillingen som [the current job that was applied for] (will be taken from drupal as well). 
Hvis du har spørgsmål angående stillingen, er du velkommen til at kontakte [hiring managers name] på [hiring managers phone] eller [hiring managers email]. 

Vi ønsker dig held og lykke med det videre forløb. 

Venlig Hilsen
SkillsPeople Teamet'

you thing this is possible? :D i know i suddenly have a looooot for you to do, i hope you are up for it :)

**Comment by mamont77** [comment]
Done.
Result:
![website apply job posting request podio id 74412b40ab - rusla 02-10-2015 13 02 50](https://cloud.githubusercontent.com/assets/970967/6126139/f80afa2c-b125-11e4-9eb9-d7575479f675.png)

**Comment by AmandaBekhoj** [comment]
very cool! thanks! :D
