### ISSUE TITLE
tag kandidattest - page 

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#142]
christian wants some changes to this page. 
1. he wants the 'hvor ønsker du job' *(where do you want job)* - *region* and 'hvilke job er du interesseret i' *(what jobs you are interested in)* - *category* to be besides each other. so, the 'hvilke job er du interesseret i' column should be in the left side, and the 'hvor ønsker du job' should be in the right side. 
2. i made a new list with categories to be ticked of, called 'Hvilke teknologier/producenter foretrækker du at arbejde med' *(what technologies* / *manufacturers prefer to work with)*, and christian wants it to be placed like this : 
![skaermbillede 2015-02-10 kl 14 04 43](https://cloud.githubusercontent.com/assets/8081414/6127654/c8c611b8-b12d-11e4-826d-4748452ea449.png)
with 4 rows, two of them should have 7 categories and two of them should have 6 categories. 

does this make sense?

**Comment by mamont77** [comment]
The first task without problems, it is easy.
The second task, it can not be done using a module (drupal webforms) that we use. Or I can do, but I spend a lot of time for it.
1. This list is not associated with the taxonomy, just list. Very difficult to add a counter of jobs.
2. Charcoal (dark grey) color I can do it easily.
2. About  4 rows (maybe cells?), i can use CSS grid system, but in this case: 7 + 7 + 7 + 3 or 4 + 4 + 4 + 4. Drupal does not allow cutting by our rules, or it will be difficult to implement. And if you add or remove categories, it can be broken.

**Comment by AmandaBekhoj** [comment]
hm okay. 

(it should not be charcoal, it was just to show example ;))

it is just because, it does not look good with like, one long row of things to tick off (like it is now). 

are there an other possibilities with drupal? to make it look good.

**Comment by mamont77** [comment]
I will try.It will look better.

**Comment by mamont77** [comment]
Amanda, I did some sketches on my local sandbox.
Can you review?

This variant a lot of empty space.
![1](https://cloud.githubusercontent.com/assets/970967/6184981/5cc1c0d4-b371-11e4-9e5c-d446c1d3ec81.png)

Maybe a little bit better.
![2](https://cloud.githubusercontent.com/assets/970967/6184988/79cefcb4-b371-11e4-89f5-1ebee809f69a.png)

I like it.
![3](https://cloud.githubusercontent.com/assets/970967/6184997/91d5937c-b371-11e4-881e-308cf5100358.png)

And please write comments and suggestions of course.

**Comment by mamont77** [comment]
I can push any version to the site and you will be able to try it.

**Comment by AmandaBekhoj** [comment]
i like version 2 best! please push it to the site, then i will review :)

very good work, thanks!

**Comment by mamont77** [comment]
Pushed!

**Comment by mamont77** [comment]
![upload dit cv og tag kandidattesten skillspeople - referral re 02-13-2015 12 09 18](https://cloud.githubusercontent.com/assets/970967/6185607/311d5f08-b379-11e4-8ea2-ac5ab195a850.png)

**Comment by AmandaBekhoj** [comment]
so much better!

you can make it live :)

**Comment by mamont77** [comment]
Done))

**Comment by AmandaBekhoj** [comment]
thaanks!
