### ISSUE TITLE
job category 

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#143]
we have changed the job categories. 

can i change them somewhere, or do you have to do that? 

Salg : 
Salgsdirektør
Salgschef
Key Account Manager
Account Manager
Telesalg

Teknik :
Extranet/Intranet/Portal/CMS konsulent
CRM konsulent
BI Konsulent
IT infrastruktur konsulent
Projektleder
Softwareudvikler
Security konsulenter
IT ledelse

**Comment by mamont77** [comment]
yes, you can http://www.skillspeople.dk/admin/structure/taxonomy/job_categoty

**Comment by AmandaBekhoj** [comment]
thanks, i will fix it :D
