### ISSUE TITLE
New field when creating job

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#145]
I know, it is a never ending task :)

right now, when advisors apply or refer a candidate, and when anonymous apply, a mail is generated to email pt@skillspeople.dk. He is no longer with us, so this responsible needs to be moved

i need a field on each job site (only available for admin) where i can write the email to the person who should get this information instead of pt@skillspeople.dk. 

There will be different people to handle different jobs, therefore i should be able to have a different email to different jobs :)

does this make sense?

**Comment by mamont77** [comment]
How to name this field?

**Comment by AmandaBekhoj** [comment]
call it: 
Talent Manager

**Comment by mamont77** [comment]
Done. Please update all jobs ;-)

**Comment by AmandaBekhoj** [comment]
perfect :dancer:
