### ISSUE TITLE
Review sitemap file

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#146]
Amanda, please review http://www.skillspeople.dk/sitemap.xml.
Perhaps in this file has links that should not be added to the search engines.
Write a list of the pages.

**Comment by AmandaBekhoj** [comment]
i don't know exactly what you mean?

**Comment by mamont77** [comment]
Sorry, I was too lazy to explain.

Site has the module - Who creates an XML sitemap conforming to the sitemaps.org protocol to help search engines find and index pages on your site.

In some cases, the file may contain the old pages (for example to remove the link from the menu, but the page still exists). In fact, Google (or other spider) continues to index the page and display it in search results.

Just look at links from the file, and we remove old pages if there are any.

**Comment by AmandaBekhoj** [comment]
http://www.skillspeople.dk/badass-drupal-developer-e-conomic-0
http://www.skillspeople.dk/forsikringssaelger-koebenhavn-vardia
http://www.skillspeople.dk/net-back-end-developer-koebenhavn-gn-netcom
http://www.skillspeople.dk/privacy-policy
http://www.skillspeople.dk/salgskonsulent-koebenhavn-lo-plus
http://www.skillspeople.dk/udviklerjavascript-koebenhavn-codesealer

these do not exist anymore :)
there are also some of the links, that are there two times?

**Comment by mamont77** [comment]
Fixed.
