### ISSUE TITLE
job search interface for mobile devices

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#147]
Continued from #127.

https://github.com/mamont77/skillspeople/issues/127#issuecomment-74479875

**Comment by AmandaBekhoj** [comment]
perfect :)

**Comment by mamont77** [comment]
i tried to move all blocks to right sidebar on my local sandbox
![find job skillspeople - referral recruitment kobenhavn - goog 02-16-2015 11 32 56](https://cloud.githubusercontent.com/assets/970967/6209535/a8ab8a24-b5cf-11e4-9915-45c2f1b3a571.png)

but it was applied globally
![sadan imodekommer vi dine forventninger skillspeople - referra 02-16-2015 11 34 35](https://cloud.githubusercontent.com/assets/970967/6209581/db3debee-b5cf-11e4-9352-11c1d31b1ca9.png)
 
So use mobile detector module is better idea.

**Comment by AmandaBekhoj** [comment]
yes, i do not like this!
mobile detector module is the way to go!

**Comment by mamont77** [comment]
Done. I think it's better now.
Please check carefully.

![screenshot_2015-02-16-13-25-47](https://cloud.githubusercontent.com/assets/970967/6211353/90cd8c38-b5e1-11e4-9394-c3be7c68c301.png)
![screenshot_2015-02-16-13-25-58](https://cloud.githubusercontent.com/assets/970967/6211354/90cf55ae-b5e1-11e4-9d9c-bb976082ad33.png)
![screenshot_2015-02-16-13-38-40](https://cloud.githubusercontent.com/assets/970967/6211355/90d1dc7a-b5e1-11e4-91ff-ed4a6cea86c2.png)
![screenshot_2015-02-16-13-38-49](https://cloud.githubusercontent.com/assets/970967/6211356/90d47c6e-b5e1-11e4-999f-c2453ac34b69.png)
![screenshot_2015-02-16-13-38-56](https://cloud.githubusercontent.com/assets/970967/6211357/90dad410-b5e1-11e4-8053-63fa29830b44.png)

**Comment by AmandaBekhoj** [comment]
i think it looks much better :)

but it will not be placed on the 'right' side on the webpage?

**Comment by mamont77** [comment]
In fact, it is placed on the right side. But only for mobile devices. These devices have a small width of the screen, and therefore the right side floats down.

**Comment by AmandaBekhoj** [comment]
coooool! but i think it is much better!

**Comment by mamont77** [comment]
Can we close an issue?

**Comment by AmandaBekhoj** [comment]
yes, sorry!
