### ISSUE TITLE
Henvis Kandidat! (left block) - should go to Zoho

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#149]
As part of this #148 task.

Block is visible adviser only!

**NOW!**
Fields list:
* Advisor ID
* Navn på kandidaten *
* Kandidatens E-mail adresse *
* Kandidatens telefonnummer
* Kommentarer fra Advisor
* job_podio_id (hidden like XFD45DFR)
* job_title (hidden like "Senior Sales Specialist - Silkeborg - Coresec Systems A/S")
* job_full_title (hidden like "2 - Senior Sales Specialist - Silkeborg - Coresec Systems A/S")

After submit sends (export) all data to podio apps.

**IT SHOULD BE!**

The form does not change.
Instead of sending to podio using podio API -> sends to zoho as mail (hnsrdv@resumes.zohorecruit.com) with...
Subject: 
`Job ID [job_podio_id's field value], SkillsPeople.dk`
Body: 
```
Advisor ID: [13213]
Navn på kandidaten: [Advisor name]
Kandidatens E-mail adresse:  [Advisor mail]
Kandidatens telefonnummer: [Advisor phone]
Kommentarer fra Advisor: [Advisor comment]
Job ID: [XFD45DFR]
Job: ["Senior Sales Specialist - Silkeborg - Coresec Systems A/S"]
```

Is it Correct?

**Comment by AmandaBekhoj** [comment]
yes, it is correct!

**Comment by mamont77** [comment]
Fixed the "Henvis Kandidat!" block and  /henvis-potentiel-kandidat page!
Need to test.

**Comment by AmandaBekhoj** [comment]
hm, i tried to Henvis Kandidat. 

this is how the information is written in Zoho
![skaermbillede 2015-02-18 kl 14 01 38](https://cloud.githubusercontent.com/assets/8081414/6247633/0b6b9fc0-b777-11e4-8759-fe7db72f791e.png)

It has not been linked to any specific job. as far as i can se. i will ask Christian to investigate. 


Also - the advisor that refers the candidate, should receive an email, i thought that it was already set up, but i did not receive anything?

**Comment by AmandaBekhoj** [comment]
also, it should say 'Tak for din henvisning' 

(since the advisors should not be contacted again :)

![skaermbillede 2015-02-18 kl 14 08 31](https://cloud.githubusercontent.com/assets/8081414/6247715/1f20981c-b778-11e4-832e-7986fb6cf7b9.png)

**Comment by AmandaBekhoj** [comment]
but - when i use the 'henvis kandidat' form on the henvis-potentiel-kandidat page it does not transfer to Zoho?

**Comment by mamont77** [comment]
Ready to testing.
The form uses Zoho API.
![zoho recruit - google chrome 02-19-2015 17 34 15](https://cloud.githubusercontent.com/assets/970967/6270205/e74e86d0-b860-11e4-8b3f-f0e06b420e0a.png)

**Comment by AmandaBekhoj** [comment]
i will test tomorrow with christian :)

**Comment by AmandaBekhoj** [comment]
so, it looks like it works much better :D and all the information is on the right place!

**Comment by AmandaBekhoj** [comment]
i will close this
