### ISSUE TITLE
Søg stillingen - should go to Zoho

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#150]
As part of this #148 task.

*FOR NOW*
```
A fields list:

* First Name *
* Last Name *
* E-mail *
* CV upload  
```
After submitting the form drupal send 4 emails.
```
$to = 'hnsrdv@resumes.zohorecruit.com';

Subject:
'JobId: [JobID], SkillsPeople.dk'

Body:
Name: [first_name  last_name]
Email: [mail]
Advisor Podio ID: [advisor_podio_id]
Job ID: [podio_id]
Job title: [job_title]
Request URL: [link to job]
+ attachennt (cv)
```
then
```
$to = $talent_manager_mail + $manager_mail (mails from node)

Subject:
'Ny candidate far SkillsPeople til stillingen [job_title]

Body:

Body:
Name: [first_name  last_name]
Email: [mail]
Advisor Podio ID: [advisor_podio_id]
Job ID: [podio_id]
Job title: [job_title]
Request URL: [link to job]
+ attachennt (cv)
```
and then
```
$to = user mail (from form)

Subject:
'Job: [job_title], SkillsPeople.dk'

Body:

Hej <strong>[first_name]</strong>
Mange tak for din ansøgning til stillingen som <strong>[job_title]</strong>.
Hvis du har spørgsmål angående stillingen, er du velkommen til at kontakte <strong>[manager_fname]</strong> på <strong>[manager_phone]</strong> eller <strong>[manager_mail]</strong>.
Vi ønsker dig held og lykke med det videre forløb.
--
Venlig Hilsen
SkillsPeople Teamet
```

This logic was changed yesterday in #148.
Please review and confirm.

**Comment by AmandaBekhoj** [comment]
okay i tested:
1. the hnsrdv@resumes.zohorecruit.com mail did not get the right mail, it got the same mail as the hiring manager
![skaermbillede 2015-02-18 kl 11 21 20](https://cloud.githubusercontent.com/assets/8081414/6245561/57368ff8-b760-11e4-984b-6be5411ef4c1.png)
christian will check if it got into Zoho as it should. 

2. the text is wrong (but i know it is my fault, it autocorrected me). the subject should read 'Ny kandidat fra SkillsPeople til stillingen [short job title]
Also, it should not contain Advisor ID and Job ID

3. this mail is very good :)

**Comment by AmandaBekhoj** [comment]
so, the application is going to Zoho, but the one i made, the test one, did not have any information other than the CV..

**Comment by mamont77** [comment]
Amanda,

I made some changes. Should be tested.

Example: http://www.skillspeople.dk/job/sharepointkonsulenter-koebenhavn-aarhus-innofactor

The data from form:
```
//    [advisor_first_name] => Ruslan
//    [advisor_last_name] => Piskarev
//    [advisor_drupal_mail] => ruslan.piskarev@gmail.com
//    [nid] => 98
//    [job_podio_id] => 0F9CF6E00C
//    [job_title] => Sharepointkonsulenter - København & Århus - Innofactor A/S
```

First mail
```php
hnsrdv@resumes.zohorecruit.com
Array
(
    [subject] => JobId: 0F9CF6E00C, SkillsPeople.dk
    [body] => Array
        (
            [0] => Name: Ruslan Piskarev

Email: ruslan.piskarev@gmail.com

Job title: Sharepointkonsulenter - København & Århus - Innofactor A/S

Request URL: http://www.skillspeople.dk/job/sharepointkonsulenter-koebenhavn-aarhus-innofactor
        )

)
````

Second mail
```php
dt@skillspeople.dk
Array
(
    [body] => Array
        (
            [0] => Name: Ruslan Piskarev

Email: ruslan.piskarev@gmail.com

Job title: Sharepointkonsulenter - København & Århus - Innofactor A/S

Request URL: http://www.skillspeople.dk/job/sharepointkonsulenter-koebenhavn-aarhus-innofactor
        )

    [subject] => Ny kandidat fra SkillsPeople til stillingen Sharepointkonsulenter - København & Århus - Innofactor A/S
)
```

Mail to me
```php
ruslan.piskarev@gmail.com
Array
(
    [subject] => Job: Sharepointkonsulenter - København & Århus - Innofactor A/S, SkillsPeople.dk
    [body] => Array
        (
            [0] => Hej Ruslan
Mange tak for din ansøgning til stillingen som Sharepointkonsulenter - København & Århus - Innofactor A/S.
Hvis du har spørgsmål angående stillingen, er du velkommen til at kontakte Dorte Thorsted på 26235871 eller dt@skillspeople.dk.
Vi ønsker dig held og lykke med det videre forløb.
--
Venlig Hilsen
SkillsPeople Teamet
        )
)
```

In all of these data correctly? Do not pay attention to job_podio_id, it's just test.

**Comment by AmandaBekhoj** [comment]
i have now edited all jobs so that they have Zoho ID, i will test.

**Comment by AmandaBekhoj** [comment]
okay, så the emails are all good now! :+1: 

So, for advisors it works. YAAY
But for anonymous applicants, we need to sync the first name, last name, and email also :)
or is that another issue? :))

**Comment by mamont77** [comment]
Ok, let me check.

**Comment by AmandaBekhoj** [comment]
like this: 

![skaermbillede 2015-02-18 kl 13 36 40](https://cloud.githubusercontent.com/assets/8081414/6247366/f02ac310-b773-11e4-978d-2077e3a0c005.png)

**Comment by mamont77** [comment]
Amanda, 

This task ready to testing. Drupal uses Zoho API now.

![zoho recruit - google chrome 02-19-2015 17 15 35](https://cloud.githubusercontent.com/assets/970967/6269428/c5a0a5fe-b85b-11e4-830d-dd937098efd5.png)

**Comment by AmandaBekhoj** [comment]
So, it partly works :) 

when i a apply as advisor - i all goes smoothly! Zoho is updated, and all the mails are going out correctly. 

When i apply as anonymous - all the mails go out correctly, but it is updated to soho two times. 
first, it is correct with the right information and the CV uploaded as well. 

but then it makes a duplicate
![skaermbillede 2015-02-20 kl 15 16 45](https://cloud.githubusercontent.com/assets/8081414/6287720/0ceb4abe-b914-11e4-8817-73b1e979ab58.png)

and there is no information in it, only the CV that i uploaded
![skaermbillede 2015-02-20 kl 15 16 58](https://cloud.githubusercontent.com/assets/8081414/6287733/181593e0-b914-11e4-9c92-4df553fd187a.png)

very weird

**Comment by mamont77** [comment]
I found!
![zoho recruit - google chrome 02-25-2015 11 06 16](https://cloud.githubusercontent.com/assets/970967/6367750/dfd92e3c-bcde-11e4-8e1e-7a09c99b4c2b.png)

1 step:
drupal send a data using Zoho API.

2 step:
drupal send a mail to hnsrdv@resumes.zohorecruit.com because in http://www.skillspeople.dk/node/98/edit Talent Manager =  hnsrdv@resumes.zohorecruit.com

3 step:
If the letter was received using "Inbox Resume" - attachment saved as separate records.

So, you can not use  hnsrdv@resumes.zohorecruit.com for Talent Manager as value.

Please double check.

**Comment by AmandaBekhoj** [comment]
ah okay, makes sense!

**Comment by AmandaBekhoj** [comment]
just tested, and it seems like it works :)
