### ISSUE TITLE
Del med dit netværk - has this somethign to do with Zoho?

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#151]
As part of this #148 task.

A field list:
Navn *
E-mail *

After submitting the form drupal send 1 email.

```php
'subject' => [name]  sender dig dette jobopslag',

  $body[] =
    'Hej <b> [name] </b>,<br />' .
    '<h4> [job title] </h4><br />' .
    '<div> [job body] </div><br />' .
    '<div>Request URL: http://www.skillspeople.dk' . request_uri() . '</div>';
```

so in this form, no changes are necessary. This form does not send data to podio and should not send data to Zoho.

Is it correct?

**Comment by AmandaBekhoj** [comment]
yes, this is correct!
