### ISSUE TITLE
Import (sync) users from Zoho DB to Drupal DB

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#154]
Amanda, please provide me any info, link or other :-)

**Comment by AmandaBekhoj** [comment]
i will ask christian tomorrow, i do not have the right access :)

**Comment by AmandaBekhoj** [comment]
christian sent you a mail with details. was it the ones you needed??

**Comment by mamont77** [comment]
yes, thanks a lot

**Comment by mamont77** [comment]
Amanda,

Can you translate it to Danish?

```
[user:name-raw],

Your account at [user:name-raw] has been activated.

You may now log in by clicking this link or copying and pasting it into your browser:

[user:one-time-login-url]

This link can only be used once to log in and will lead you to a page where you can set your password.

After setting your password, you will be able to log in at [site:login-url] in the future using:

username: [user:name-raw]
mail: [user:mail]

--  [site:name] team
```

**Comment by AmandaBekhoj** [comment]
[user:name-raw],
Din bruger [user:name-raw] er blevet aktiveret.
Du kan nu logge ind ved at klikke på dette link, eller ved at sætte det ind i din browser:
[user:one-time-login-url]
Dette link kan kun blive brugt én gang til at logge ind midlertidigt, herefter skal du lave en ny kode, som du kan bruge når du skal logge ind på [site_login-url].

Brugernavn: [user:name-raw]
Mail: [user:mail]

--  [site:name] team

**Comment by mamont77** [comment]
Yay! We did it!
I'll be watching for several days. Then will close.

**Comment by mamont77** [comment]
Fixed. tested and closed.
