### ISSUE TITLE
drupal 'thank you message'

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#156]
so, you remember that i wanted to change the message in the green box that appears when you 'Henvis Kandidat' since it said 'thank you for applying, we will get in tough with you soon. 

anyway, i changed it through the link you sent me. I made it say 'Tak for din henvisning', but this message also appears when applying for the job, which should have the previous message. 

also, it duplicates.. 
 This came up when i applied for a position 
![skaermbillede 2015-02-20 kl 15 15 23](https://cloud.githubusercontent.com/assets/8081414/6287830/df328c8a-b914-11e4-9d46-be25fc77dae0.png)

can i not have different messages for different functions?
Tak for din henvisning - when referring
Tak for din ansøgning, vi vender tilbage hurtigst muligt - when applying for a job
Jobbet er nu delt - when sharing the job position with someone 

possible?

**Comment by mamont77** [comment]
Fixed.
Please test.
A message may be shown two times in the case of when the form has been sent two times.

**Comment by AmandaBekhoj** [comment]
perfect, it works :)
