### ISSUE TITLE
Drupal CV upload

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#157]
So, as the Zoho sync is starting to look much better, we need to fix this task. 

The candidate information from 'CV upload og Kandidattest' should also into Zoho! 

There are now 20 candidates who has uploaded their CV (and only some of them took the test). 

We need all the information to go to Zoho, as if it was linked to a job - but the job should be called 'CV Upload' .. 

Information to go to Zoho: 
Job : CV Upload (i can create the job in Zoho and provide you with an Zoho ID, do you need this?)
Name
Phone
Email
Nuværende job (current position)
Region
Hvilke job er du interesseret i (what jobs are you interested in)
Hvilke teknologier foretrækker du at arbejde med (What technologies do you prefer)

and then also the CV. 

in terms of the 20 there already is, should we put them in manually, or can you sync them when you connect drupal with Zoho?

**Comment by mamont77** [comment]
>> in terms of the 20 there already is, should we put them in manually, or can you sync them when you connect drupal with Zoho?

I can spend about 4 hours to do this, but this is not the appropriateness.
Please put them in manually.

Described the task excellent!

**Comment by AmandaBekhoj** [comment]
we will do it manually on monday :)

thanks, i was also really concentrated ;)

**Comment by mamont77** [comment]
Done. Ready to testing.
![zoho recruit - google chrome 02-20-2015 18 13 51](https://cloud.githubusercontent.com/assets/970967/6289945/5c123220-b92c-11e4-8f45-bd0b92da9a00.png)

**Comment by AmandaBekhoj** [comment]
it works good, thanks! :dancer:
