### ISSUE TITLE
ASAP - smtp.office365.com doesn't work

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#158]
Hi Amanda,

This does not work for 2 days. Yesterday I sent a letter to Christian and you. You got it?

**Comment by AmandaBekhoj** [comment]
yes, but i did not know what i was about.
we got new user information, does this help?
User Name: noreply@skillspeople.dk
Temporary Password: Bata2852

**Comment by mamont77** [comment]
No, this doesn't help.
SMTP -> ERROR: Password not accepted from server: 535 5.7.3 Authentication unsuccessful 

Ok, I will explore :-(

**Comment by AmandaBekhoj** [comment]
let me know if you need anything :)

**Comment by mamont77** [comment]
Fixed. I will sent a new password to mail.

**Comment by AmandaBekhoj** [comment]
you are a superstar :D
