### ISSUE TITLE
extended menu does not work

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#162]
Hi Ruslan, 

it seems like the problems won't stop today. 

så, the extended menu won't work. usually, when i hold the mouse over 'ledige stillinger' the extended menu with 'ledige stillinger - salg' and 'ledige stillinger - teknik' should pop up, but it does not :(

![skaermbillede 2015-03-02 kl 15 19 57](https://cloud.githubusercontent.com/assets/8081414/6442426/e62dfe92-c0ef-11e4-8487-c21cb60e61b4.png)

**Comment by mamont77** [comment]
Sorry.
Its my bad.
When I searched ajax error, i set old version jquery. And forgot to revert back. Fixed. My apologies.

**Comment by AmandaBekhoj** [comment]
no worries :)
