### ISSUE TITLE
one more green message

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#163]
So, when you go to 'Kontakt' and submit a contact form, then the 'Tak for din henvisning' message comes up again, but it should read 'Tak for din forespørgsel – vi kontakter dig snarest'

can you fix? last time i fixed, i messed everything up :(

**Comment by mamont77** [comment]
I can see this message "Din besked er blevet sendt." (Your message has been sent.) after http://www.skillspeople.dk/contact form submitting. 

I fixed as you asked. http://www.skillspeople.dk/admin/config/regional/translate/edit/8168

Please check.

**Comment by AmandaBekhoj** [comment]
hm, whenever i submit my details in the contact field, i go to the front page when i submit? so, i am not sure if i submitted?

**Comment by mamont77** [comment]
Amanda,

Good found.

This Drupal comment on the matter.
// Jump to home page rather than back to contact page to avoid
// contradictory messages if flood control has been activated.

We do not have similar functionality, so I corrected redirect to /contact.
Was fixed for skillspeople, infrahouse and salestribe.

**Comment by mamont77** [comment]
Please check the message, i see "Din besked er blevet sendt" steel.

**Comment by AmandaBekhoj** [comment]
hm, now it says this: the red box says 'your message cannot be sent' and then the green box says, 'your message has been sent'

very strange 
![skaermbillede 2015-03-04 kl 10 12 21](https://cloud.githubusercontent.com/assets/8081414/6480731/24aacdfe-c257-11e4-85b7-4e469142175b.png)

**Comment by mamont77** [comment]
I got this.

It looks like smtp.office365.com blocks as spam. Such were a few days ago. I'm checking.

**Comment by mamont77** [comment]
I went to the site https://outlook.office365.com/ and it automatically unlock sending emails. 
And i can see
![no reply - skillspeople - outlook web app - google chrome 03-04-2015 11 35 50](https://cloud.githubusercontent.com/assets/970967/6481071/bdba7f52-c262-11e4-92f1-3d7b2be66480.png)

check again.

**Comment by AmandaBekhoj** [comment]
it still gives both the red box and green box, as shown above :(

**Comment by mamont77** [comment]
It seems it works now.
![1](https://cloud.githubusercontent.com/assets/970967/6482878/8ce02524-c273-11e4-909b-5a84613585bf.png)

**Comment by AmandaBekhoj** [comment]
i just tested, and it did not work :(

**Comment by mamont77** [comment]
ah.
I will add your and mine email in recipients. May be it will help.
In process, debuging.

**Comment by mamont77** [comment]
Amanda,
can you see it in your mailbox?
![website feedback message from ruslan - ruslan piskarev gmail c 03-04-2015 16 41 10](https://cloud.githubusercontent.com/assets/970967/6485596/779e1cce-c28d-11e4-823b-b6010e106b0a.png)

**Comment by mamont77** [comment]
Amanda,

I tried use ab@infrahouse.com as value "Din e-mail-adresse" field and got same error :-) 
Can you try use other mail?
I'm not sure. I have a suspicion that your email gets rejected postal service. Maybe I was wrong.

**Comment by AmandaBekhoj** [comment]
i get all the emails to my mailbox! i will test my email in the contact form

**Comment by AmandaBekhoj** [comment]
hm yes you are right, now it works with another email!

**Comment by mamont77** [comment]
I hope your email - it's temporary trouble :-D.

**Comment by AmandaBekhoj** [comment]
hehe me too :b
