### ISSUE TITLE
security update

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#165]
i keep getting mails about a security for drupal, is it something i can install myself?

**Comment by mamont77** [comment]
You can, but I do not recommend it, it can break the site.
In addition, I use GIT for storage the history of changes.
The best way to create a task like this :-)
I added you to the mail list, just in case I will not be available for several days.
If you want, you or i can remove your email from this list.
http://www.skillspeople.dk/admin/reports/updates/settings

I'll update the critical modules now.

**Comment by mamont77** [comment]
Fixed.

**Comment by AmandaBekhoj** [comment]
super, thanks :)

maybe best i not touch it if i can break the site! sounds like something that i would do :b
