### ISSUE TITLE
Zopim notice

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#166]
I see a note in java script. This is not critical, but it is better to fix.
![skillspeople - referral recruitment kobenhavn - google chrome 03-04-2015 09 34 36](https://cloud.githubusercontent.com/assets/970967/6479664/d8ca6980-c251-11e4-8a0b-2baa1e1c0a3f.png)

**Comment by mamont77** [comment]
Fixed.
Now works autologin in Zopim  for advisors.
![skillspeople - referral recruitment kobenhavn - google chrome 03-04-2015 09 46 02](https://cloud.githubusercontent.com/assets/970967/6479783/6d245338-c253-11e4-84ba-6f4ead5d9a21.png)

**Comment by AmandaBekhoj** [comment]
ah, that is perfect, thanks :D
