### ISSUE TITLE
Job Posting - delete publication date

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#167]
hi ruslan, 

is it possible to remove the publication dates on the jobs? 
![skaermbillede 2015-03-06 kl 13 04 17](https://cloud.githubusercontent.com/assets/8081414/6525082/6102ad20-c401-11e4-9d6f-30d3a32a7675.png)

**Comment by mamont77** [comment]
Fixed.

I'm not sure, it may be more informative if we add a category instead of the date.
>>Category: Extranet/Intranet/Portal/CMS konsulent | Region: Midtjylland

**Comment by AmandaBekhoj** [comment]
yea good idea!

**Comment by mamont77** [comment]
Completed.
Please check.
![find job skillspeople - referral recruitment kobenhavn - goog 03-06-2015 14 27 15](https://cloud.githubusercontent.com/assets/970967/6525336/08fd5538-c40d-11e4-85ca-eed2d22a310d.png)

**Comment by AmandaBekhoj** [comment]
much better, thanks!
