### ISSUE TITLE
Vores Advisors page

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#169]
Hi Ruslan, 

I have made this page, but you know - my coding skills are not too developed as yet!

So, i wondered if you could help me with a few things before i publish the site
http://www.skillspeople.dk/vores-advisors

I have made some bullets, there are ten, and i would like to have 5 in one row, and then 5 in another row beside it. 

Also, i have two images and descriptions of the images, and i want to have the images and descriptions to be beside each other as well. 

lets see if i can demonstrate it :)

![skaermbillede 2015-03-06 kl 16 20 12](https://cloud.githubusercontent.com/assets/8081414/6527803/fff3e7d4-c41d-11e4-95cf-dc2a25f8248b.png)

oh my god, so many boxes and arrows! i hope it makes sense?

**Comment by mamont77** [comment]
Hi Amanda,

Not a problem. I will do not later than Monday. Over the weekend, I'm not available.

**Comment by AmandaBekhoj** [comment]
of course, no problem :)

**Comment by mamont77** [comment]
Done.

Result:

PC
![vores advisors skillspeople - referral recruitment kobenhavn 03-08-2015 08 04 12](https://cloud.githubusercontent.com/assets/970967/6544812/d7ae4088-c569-11e4-88a1-5045bb5c2e55.png)

Mobiles
![vores advisors skillspeople - referral recruitment kobenhavn 03-08-2015 08 06 39](https://cloud.githubusercontent.com/assets/970967/6544820/30a10dba-c56a-11e4-8237-67395f20db79.png)

**Comment by AmandaBekhoj** [comment]
thank you :D
