### ISSUE TITLE
images on jobpages

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#170]
Hi Ruslan, 

I hope you had a good birthday yesterday! 

I have an odd question. We now use Zoho Campaigns for posting on our social media sites. However, we have some problems with the images when we use a link from skillspeople.dk. 

We usually use the links for job pages, and then we would want the logo from the drupal page, to appear on our social media posts. BUT - here comes the problem - When we put the drupal link into the Zoho Campaigns system, then it can only find the SkillsPeople logo, and not the logo for the job page. is there anyway the image is not connected to the link or something? 

It is a little weird, because when i use Zoho Campaigns with InfraHouse, then the images i use for a specific page, e.g. the blog, will appear in Zoho Campaign and then i can choose them. 

I know this is a weird question, and it might be badly described. sorry!

**Comment by mamont77** [comment]
Can you provide me any example?

**Comment by AmandaBekhoj** [comment]
yes, 

first you see the the zoho campaign interface when i use a skillspeople link - then there is only one image to chose from - the skillspeople logo - even though the link is to a job page, where there is another image connected. 
![skaermbillede 2015-03-12 kl 09 26 17](https://cloud.githubusercontent.com/assets/8081414/6614437/71a54280-c89a-11e4-9e1a-3852364d5e17.png)

next is the case when i use a infrahouse link to one of the blogposts - here i can choose between 6 different images, thhe infrahouse logo, the social media icons, the flags, and the image i have posted with the blog.. 

![skaermbillede 2015-03-12 kl 09 28 51](https://cloud.githubusercontent.com/assets/8081414/6614461/bef84028-c89a-11e4-90f5-891735913aaf.png)

so my question is, whether the image posted on the skillspeople job posts, are not recognized as images in some way? since they do not appear when i use the link in zoho?

**Comment by mamont77** [comment]
I tried to increase the logo and turn on the metatags module (http://www.skillspeople.dk/admin/config/search/metatags).
http://www.skillspeople.dk/job/senior-udviklerloesningsarkitekt-til-odense-tv-2
![senior udvikler losningsarkitekt til - odense - tv 2 skillspeo 03-12-2015 12 55 25](https://cloud.githubusercontent.com/assets/970967/6616489/207cc1e0-c8b7-11e4-95a4-352c68d1f618.png)
It seems it works now.
![zoho campaigns - google chrome 03-12-2015 12 55 00](https://cloud.githubusercontent.com/assets/970967/6616505/3d562ebe-c8b7-11e4-8b93-ae325a56e404.png)

**Comment by AmandaBekhoj** [comment]
you are a superstar :D

**Comment by AmandaBekhoj** [comment]
i think it is not good after you made the images bigger - it does not work well when we use soho campaigns .. 
![skaermbillede 2015-03-17 kl 14 45 40](https://cloud.githubusercontent.com/assets/8081414/6688535/80fe57f8-ccb4-11e4-9419-b8ebead2bed8.png)

**Comment by mamont77** [comment]
I can reduce the image. What are the dimensions set?

**Comment by AmandaBekhoj** [comment]
im not sure.. they are set by Facebook and linkedin.

again, it works when i use Infrahouse links, but not when i use skillspeople links.. 
you know what the dimensions are for the images on infrahouse blogposts? (infrahouse blogposts are the only things i post through soho campaigns)

**Comment by mamont77** [comment]
The Infrahouse has more square pictures.
Jops logo has a large width and a small height.
Therefore, it happens.

As solution:

I added second square logo and made this not visible for visitors, but it is visible for Zoho.

![sharepoint account manager - kobenhavn - innofactor skillspeop 03-17-2015 19 02 00](https://cloud.githubusercontent.com/assets/970967/6692905/3eb63482-ccd8-11e4-821b-9675ec840135.png)

I hope this will help to deceive Zoho!

![zoho campaigns - google chrome 03-17-2015 19 10 07](https://cloud.githubusercontent.com/assets/970967/6693224/1a6e6cdc-ccda-11e4-8d32-db92dfc9db31.png)
![zoho campaigns - google chrome 03-17-2015 19 13 48](https://cloud.githubusercontent.com/assets/970967/6693225/1a7032ba-ccda-11e4-941c-51b0e2a0d25e.png)
![zoho campaigns - google chrome 03-17-2015 19 15 24](https://cloud.githubusercontent.com/assets/970967/6693226/1a742500-ccda-11e4-893c-9c2fd2fb4957.png)


Can you check?

**Comment by AmandaBekhoj** [comment]
seems better :) thanks!
