### ISSUE TITLE
ekstra field on job pages

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#172]
So, we need an extra mandatory field when creating a job post, which should be called 
SkillsPeople Partner

and it should contain a mail. 

it is the same as the Talent Manager field - the SkillsPeople partner should get an email every time someone applies for a job :)

**Comment by mamont77** [comment]
A new field has been created.
Can you update one job?
http://www.skillspeople.dk/node/123/edit
So i can continue "mail sending".

**Comment by mamont77** [comment]
Done.

**Comment by AmandaBekhoj** [comment]
i have updated in two jobs now :)

**Comment by mamont77** [comment]
so you can test mail

**Comment by AmandaBekhoj** [comment]
perfect it works :)
