### ISSUE TITLE
More search fields

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#173]
So there are several tasks:

1. the search button that already exist should have our orange color with white font, so it is easier to see. i tried to find the button properties, but failed.. 

2. we need a 'Søg stillingen' under the contact information on the left. also orange button with white font - maybe it is ugly, i do not know :b 
![skaermbillede 2015-03-13 kl 11 28 08](https://cloud.githubusercontent.com/assets/8081414/6636840/30afe192-c974-11e4-8f23-3ee4f0c39e43.png)

3. for advisors, there is the 'Henvis Kandidat' in the button of the job posting, for anonymous users, it should say 'Søg Stillingen' in orange font. 

![skaermbillede 2015-03-13 kl 11 31 32](https://cloud.githubusercontent.com/assets/8081414/6636893/90137f40-c974-11e4-919c-3085a7800c84.png)

all these buttons should look the same and require the same, name, last name, email, and CV upload.

Does this make sense? :)

**Comment by mamont77** [comment]
If I understand you correctly, we duplicate the functionality of the block on the left. But in orange.

![front-end developer - kobenhavn - penneo skillspeople - referr 03-13-2015 12 57 13](https://cloud.githubusercontent.com/assets/970967/6637230/9ea4ba68-c980-11e4-82fe-e01e461e3ffa.png)

**Comment by AmandaBekhoj** [comment]
yes :)

**Comment by mamont77** [comment]
Ready for testing.
Do this very carefully!
![sharepoint account manager - kobenhavn - innofactor skillspeop 03-13-2015 15 38 35](https://cloud.githubusercontent.com/assets/970967/6639303/33e53a10-c997-11e4-847f-3ecd0c4ae40a.png)

Frankly I do not like the blocks below. Three blocks a lot.

**Comment by AmandaBekhoj** [comment]
i know, but it is not me, who want all the apply buttons..sadly

but, it should not be the 'Søg' button that should be orange, but the 'Apply button' :) 

![skaermbillede 2015-03-13 kl 14 43 08](https://cloud.githubusercontent.com/assets/8081414/6639390/70064a46-c98f-11e4-8b6f-805723a11566.png)

**Comment by mamont77** [comment]
I did not understand. Please explain the last message in other words. :-)
Step by step.

**Comment by mamont77** [comment]
is it correct?
![sharepoint account manager - kobenhavn - innofactor skillspeop 03-13-2015 15 54 59](https://cloud.githubusercontent.com/assets/970967/6639567/6a8c9c28-c999-11e4-9ed0-895657b28f63.png)

**Comment by AmandaBekhoj** [comment]
i am sorry!

1. Okay, so i just talked to one of the partners, and he want the 'find job' field gone from the individual job pages for now.. He thinks too much is happening on the site.
 
this one:
![skaermbillede 2015-03-13 kl 14 54 47](https://cloud.githubusercontent.com/assets/8081414/6639557/fd464c48-c990-11e4-8235-cef5178bba71.png)

2. this button should be orange with white font:

![skaermbillede 2015-03-13 kl 14 55 43](https://cloud.githubusercontent.com/assets/8081414/6639578/1c25984e-c991-11e4-8140-4c8ede106e97.png)

3. the rest is fine, he likes all the buttons and the colors..

**Comment by AmandaBekhoj** [comment]
yes, the thing you just wrote is correct :)

**Comment by mamont77** [comment]
Done.
I don't like the "Henvis Kandidat!" and "Del med dit netværk" sizes and colors.

Maybe can we use other styles? Examples: http://getbootstrap.com/2.3.2/base-css.html#buttons

**Comment by mamont77** [comment]
And meybe wiil be better use white color for file (cv) field.
![microsoft infrastruktur konsulent - kobenhavn - infrahouse ski 03-13-2015 16 17 47](https://cloud.githubusercontent.com/assets/970967/6639951/ade54dc8-c99c-11e4-8661-1e8608f994a5.png)

**Comment by AmandaBekhoj** [comment]
good, and i got your test application, so it works :)

1. you are right with the buttons, they should be the same size as the 'søg stillingen' button.. but i think the colors are fine.. the orange one should stand out. but maybe, we should place the orange button on the top instead of the middle of the three buttons?

2. i think the CV upload looks fine for now :)

**Comment by mamont77** [comment]
Result.
![it-konsulent - kobenhavn - sopra steria skillspeople - referra 03-13-2015 16 34 52](https://cloud.githubusercontent.com/assets/970967/6640294/ffe765c8-c99e-11e4-9968-615ccb9a7e5b.png)

**Comment by mamont77** [comment]
Ready for testing.

**Comment by AmandaBekhoj** [comment]
works, thanks!
