### ISSUE TITLE
Use Zoho instead of GitHub

### ISSUE THREAD

**Issue by mamont77** [mamont77/skillspeople#174]
@AmandaBekhoj ,

Can we now or in the future use Zoho instead of GitHub issues?
Because we have a lot of tasks and it appears in the Google search results.

![skillspeople - google - google chrome 03-13-2015 16 22 33](https://cloud.githubusercontent.com/assets/970967/6640015/4a31b5e0-c99d-11e4-8ccd-fd84ace792e1.png)

**Comment by AmandaBekhoj** [comment]
wow! i though it was sort of private when you had to log in and stuff like that. but off course, we can have the issues in Zoho, where do we do it?

**Comment by mamont77** [comment]
>> it was sort of private

Yes, $25 per month. Sometimes I forget to pay on time.

>>where do we do it?

 i can see https://www.zoho.com/projects/ +  https://www.zoho.com/projects/features.html

**Comment by AmandaBekhoj** [comment]
hehe okay. i have created an account here, i think it is best
https://projects.zoho.com/portal/skillspeople/newlogin.do#allprojects

**Comment by mamont77** [comment]
Excellent. Let's try. One thing - we use Christian's account.

**Comment by AmandaBekhoj** [comment]
yes we do :)

**Comment by AmandaBekhoj** [comment]
i just made a project in Zoho, can you see it?

i feel like it does not work as well as github though :/

**Comment by mamont77** [comment]
I can see https://projects.zoho.com/portal/skillspeople#taskdetail/793104000000014017/793104000000014025/793104000000016001

But you and I use the Christian's account and we will not receive e-mail.

**Comment by AmandaBekhoj** [comment]
yes, i figured.. i just added an image :)

**Comment by mamont77** [comment]
Updated on Zoho.

Actually it is very inconvenient to leave here recording when anything is updated in Zoho.
In addition, each time the Christian receives an email, it can disturb him.

As option, I can create a new repo on https://bitbucket.org/. This is very similar to github but "Unlimited private code repositories (FREE FOR 5 USERS)".
Then delete this repo.

In any case we can try.

**Comment by AmandaBekhoj** [comment]
yes sure, it sounds like a better idea!

**Comment by mamont77** [comment]
Amanda, please check. Have you access?
https://bitbucket.org/mamont77/skillspeople/issues

**Comment by mamont77** [comment]
and I succeeded in keeping a list of tasks.
![mamont77 skillspeople issues bitbucket - google chrome 03-19-2015 09 17 41](https://cloud.githubusercontent.com/assets/970967/6725910/fa076d14-ce18-11e4-9556-374009a51ae4.png)

**Comment by AmandaBekhoj** [comment]
wow it looks good! i am now in!
