### ISSUE TITLE
Problem with one advisor

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#175]
We experience some problem with one advisor. 

He used to be able to log in, and he synced his account with LinkedIn, but now nothing works. 

He cannot remember his password, and when i send him link to change his password, it says that there is an error in username and phone number. And sometimes it says that Username does not excist. very strange. 

His username is 'Henrik Janning (Henrik Juul) Juul'
and his mail is henrik@janning-juul.dk

you know what might be wrong? or can you create temporary password for him to log in with?

**Comment by mamont77** [comment]
i set pass = 10723
![people skillspeople - referral recruitment kobenhavn - google 03-16-2015 15 22 16](https://cloud.githubusercontent.com/assets/970967/6666806/87e7642a-cbf0-11e4-826e-625c1db5ed8c.png)

**Comment by mamont77** [comment]
I think his has a long username  'Henrik Janning (Henrik Juul) Juul' and not allowed characters "( and )". Drupal does not allow it to use. I cut his name.
Please provide a new pass for Henrik.
henrik@janning-juul.dk
10723

**Comment by AmandaBekhoj** [comment]
perfect, thanks! :)
