### ISSUE TITLE
newsletter sign in

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#58]
Is it possible to make a 'Tilmeld dig votes nyhedsbrev'

It should be like a button that you press, and then you get to a form where you enter Name and email. 

Then this information should be sent to jb@skillspeople.dk

This button should only be places on the 'Hvorfor vælge os', 'Sælgere' og 'Salgsledelse'. 

![skrmbillede 2014-07-28 kl 16 18 32](https://cloud.githubusercontent.com/assets/8081414/3721629/23f34504-1662-11e4-81ce-ded811104241.png)

think this is possible?

**Comment by AmandaBekhoj** [comment]
actually, this issue can maybe finally be fixed :)

when someone sign up for our newsletter (Tilmeld dig vores nyhedsbrev)- then they should go to Zoho also! 

so, we need the information
Name
Last name
Email
![skaermbillede 2015-02-25 kl 09 42 27](https://cloud.githubusercontent.com/assets/8081414/6367406/199ba3cc-bcd3-11e4-9a1f-9d369e1c7749.png)

In Zoho, this information should be set up as 'Kunde' (customer)
with Lead Source: 'Newsletter Sign-up www'

Also, people who sign up, should receive a short email saying:
Kære [name]
Tak for din tilmelding til vores nyhedsbrev. Vi håber du vil finde indholdet behjælpeligt og interessant. 
Hvis du har spørgsmål til vores ydelser eller proces, er du velkommen til at kontakte os på [mail-to:jb@skillspeople.dk]. 

Vi ønsker dig rigtig god dag. 

Venlig Hilsen
SkillsPeople Teamet'

and one last thing - this green box needs to be corrected - i know i can do it myself, but the last time i did, i managed to screw it up!
![skaermbillede 2015-02-25 kl 09 39 41](https://cloud.githubusercontent.com/assets/8081414/6367471/d47f914e-bcd3-11e4-8cc4-7b4eab22e6f1.png)

It should say 'Tak for tilmeldingen af vores nyhedsbrev' 

i hope this makes sense :)

**Comment by mamont77** [comment]
>>In Zoho, this information should be set up as 'Kunde' (customer)
with Lead Source: 'Newsletter Sign-up www'

What the table (please provide link) or https://recruit.zoho.com/ats/Dashboard.do#Resume still?
'Kunde' - in which field it save? maybe "Position from Workable" i don't sure.
 'Newsletter Sign-up www' - where to write?

**Comment by mamont77** [comment]
>>Also, people who sign up, should receive a short email saying:

Please provide me Subject for mail.

**Comment by AmandaBekhoj** [comment]
it is on this form
https://crm.zoho.com/crm/CreateEntity.do?module=Contacts 

![skaermbillede 2015-02-25 kl 13 05 02](https://cloud.githubusercontent.com/assets/8081414/6370297/05cf2dca-bcef-11e4-989a-cd78bf93d9d8.png)


subject for mail should be 'Tilmelding til SkillsPeople nyhedsmail'

**Comment by mamont77** [comment]
Done.
Result: https://crm.zoho.com/crm/EntityInfo.do?module=Contacts&id=1125581000000350003
(please delete the record)

But I do not know how you look at this list.
https://crm.zoho.com/crm/ShowTab.do?module=Contacts

Ready for testing.

**Comment by AmandaBekhoj** [comment]
thanks!

i have deleted. 

hm, i do not know how to look at the list either, but it looks fine :) i will test!

**Comment by AmandaBekhoj** [comment]
hm.. so i tested.. and the email works fine, and i can see, that i have been added to Zoho.. but i just did not appear on the 'contact' list.. very strange?

**Comment by mamont77** [comment]
I think we can view Advisors only by default.

**Comment by AmandaBekhoj** [comment]
hm okay.. so i guess it all works as it should? :)

**Comment by mamont77** [comment]
It works as described in this task :-)

**Comment by AmandaBekhoj** [comment]
yes, thanks :D

**Comment by mamont77** [comment]
Hi Amanda,

I'm not sure how Zoho will work in this case.
Step to reproduce or example:

1. Open http://www.skillspeople.dk/hvorfor-vaelge-os
2. Enter the details of an existing advisor. ex https://crm.zoho.com/crm/EditEntity.do?module=Contacts&id=1125581000000315065 with Lead Source = Podio.
3. What happens in this case? New user is added or existing one updated or Zoho error?

Can you check?

**Comment by AmandaBekhoj** [comment]
hm, i am not sure. i tried when i was logged in as ab@infrahouse.com - and then no new contact was created.. then i tried with my other mail ab@skillspeople.dk, and i got the mail and everything, but i have not been created in zoho?

**Comment by mamont77** [comment]
I can see 
https://crm.zoho.com/crm/EntityInfo.do?module=Contacts&id=1125581000000368001
https://crm.zoho.com/crm/EntityInfo.do?module=Contacts&id=1125581000000348007

**Comment by AmandaBekhoj** [comment]
uh yes that is me. maybe it was just delayed :)

**Comment by AmandaBekhoj** [comment]
but it seems like everything is fine, since ID is not required?

**Comment by mamont77** [comment]
I was afraid it would be a error in this case. If such behavior - it's OK, you can close this issue.

**Comment by AmandaBekhoj** [comment]
cool :)
